version = "0.1.*"
requires = ["types-Pillow"]
external_requires = ["numpy", "torch", "comtypes"]

[tool.stubtest]
# TODO: figure out how to run stubtest for this package
# (the package pins Pillow in a problematic way)
skip = true
platforms = ["win32"]
