from _typeshed import Incomplete

from win32com.server.exception import Exception as Exception

class Interpreter:
    dict: Incomplete
    def __init__(self) -> None: ...
    def Eval(self, exp): ...
    def Exec(self, exp) -> None: ...

def Register(): ...
