from _typeshed import Incomplete

from pythonwin.pywin.mfc import window as window

def dllFromDll(dllid): ...

class Dialog(window.Wnd):
    dll: Incomplete
    bHaveInit: Incomplete
    def __init__(self, id, dllid: Incomplete | None = ...) -> None: ...
    def HookCommands(self) -> None: ...
    data: Incomplete
    def OnAttachedObjectDeath(self) -> None: ...
    def OnOK(self) -> None: ...
    def OnCancel(self) -> None: ...
    def OnInitDialog(self): ...
    def OnDestroy(self, msg) -> None: ...
    def AddDDX(self, *args) -> None: ...
    def __bool__(self): ...
    def __len__(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, item) -> None: ...
    def keys(self): ...
    def items(self): ...
    def values(self): ...
    def has_key(self, key): ...

class PrintDialog(Dialog):
    dll: Incomplete
    bHaveInit: Incomplete
    pInfo: Incomplete
    def __init__(
        self, pInfo, dlgID, printSetupOnly: int = ..., flags=..., parent: Incomplete | None = ..., dllid: Incomplete | None = ...
    ) -> None: ...
    def OnInitDialog(self): ...
    def OnCancel(self) -> None: ...
    def OnOK(self) -> None: ...

class PropertyPage(Dialog):
    dll: Incomplete
    def __init__(self, id, dllid: Incomplete | None = ..., caption: int = ...) -> None: ...

class PropertySheet(window.Wnd):
    dll: Incomplete
    sheet: Incomplete
    def __init__(self, caption, dll: Incomplete | None = ..., pageList: Incomplete | None = ...) -> None: ...
    def OnInitDialog(self): ...
    def DoModal(self): ...
    def AddPage(self, pages) -> None: ...
    def DoAddSinglePage(self, page) -> None: ...

def GetSimpleInput(prompt, defValue: str = ..., title: Incomplete | None = ...): ...
