from _typeshed import Incomplete

class Object:
    def __init__(self, initObj: Incomplete | None = ...) -> None: ...
    def __del__(self) -> None: ...
    def __getattr__(self, attr): ...
    def OnAttachedObjectDeath(self) -> None: ...
    def close(self) -> None: ...

class CmdTarget(Object):
    def __init__(self, initObj) -> None: ...
    def HookNotifyRange(self, handler, firstID, lastID): ...
    def HookCommandRange(self, handler, firstID, lastID): ...
    def HookCommandUpdateRange(self, handler, firstID, lastID): ...
