from _typeshed import Incomplete

from . import object as object

class WinThread(object.CmdTarget):
    def __init__(self, initObj: Incomplete | None = ...) -> None: ...
    def InitInstance(self) -> None: ...
    def ExitInstance(self) -> None: ...

class WinApp(WinThread):
    def __init__(self, initApp: Incomplete | None = ...) -> None: ...
