from _typeshed import Incomplete

from . import object as object

class Wnd(object.CmdTarget):
    def __init__(self, initobj: Incomplete | None = ...) -> None: ...
    def OnDestroy(self, msg) -> None: ...

class FrameWnd(Wnd):
    def __init__(self, wnd) -> None: ...

class MDIChildWnd(FrameWnd):
    def __init__(self, wnd: Incomplete | None = ...) -> None: ...
    def OnCreateClient(self, cp, context) -> None: ...

class MDIFrameWnd(FrameWnd):
    def __init__(self, wnd: Incomplete | None = ...) -> None: ...
