from _typeshed import Incomplete

mapCLSIDToClass: Incomplete

def RegisterCLSID(clsid, pythonClass) -> None: ...
def RegisterCLSIDsFromDict(dict) -> None: ...
def GetClass(clsid): ...
def HasClass(clsid): ...
