from _typeshed import Incomplete

from pythonwin.pywin.tools import browser
from win32com.client import util as util

class HLIRoot(browser.HLIPythonObject):
    name: Incomplete
    def __init__(self, title) -> None: ...
    def GetSubList(self): ...
    def __cmp__(self, other): ...

class HLICOM(browser.HLIPythonObject):
    def GetText(self): ...
    def CalculateIsExpandable(self): ...

class HLICLSID(HLICOM):
    def __init__(self, myobject, name: Incomplete | None = ...) -> None: ...
    def CalculateIsExpandable(self): ...
    def GetSubList(self): ...

class HLI_Interface(HLICOM): ...

class HLI_Enum(HLI_Interface):
    def GetBitmapColumn(self): ...
    def CalculateIsExpandable(self): ...

class HLI_IEnumMoniker(HLI_Enum):
    def GetSubList(self): ...

class HLI_IMoniker(HLI_Interface):
    def GetSubList(self): ...

class HLIHeadingCategory(HLICOM):
    def GetText(self): ...
    def GetSubList(self): ...

class HLICategory(HLICOM):
    def GetText(self): ...
    def GetSubList(self): ...

class HLIHelpFile(HLICOM):
    def CalculateIsExpandable(self): ...
    def GetText(self): ...
    def TakeDefaultAction(self) -> None: ...
    def GetBitmapColumn(self): ...

class HLIRegisteredTypeLibrary(HLICOM):
    def GetSubList(self): ...

class HLITypeLibEntry(HLICOM):
    def GetText(self): ...
    def GetSubList(self): ...

class HLICoClass(HLITypeLibEntry):
    def GetSubList(self): ...

class HLITypeLibMethod(HLITypeLibEntry):
    entry_type: str
    def __init__(self, ob, name: Incomplete | None = ...) -> None: ...
    def GetSubList(self): ...

class HLITypeLibEnum(HLITypeLibEntry):
    id: Incomplete
    def __init__(self, myitem) -> None: ...
    def GetText(self): ...
    def GetSubList(self): ...

class HLITypeLibProperty(HLICOM):
    id: Incomplete
    def __init__(self, myitem) -> None: ...
    def GetText(self): ...
    def GetSubList(self): ...

class HLITypeLibFunction(HLICOM):
    funckinds: Incomplete
    invokekinds: Incomplete
    funcflags: Incomplete
    vartypes: Incomplete
    type_flags: Incomplete
    id: Incomplete
    def __init__(self, myitem) -> None: ...
    def GetText(self): ...
    def MakeReturnTypeName(self, typ): ...
    def MakeReturnType(self, returnTypeDesc): ...
    def GetSubList(self): ...

HLITypeKinds: Incomplete

class HLITypeLib(HLICOM):
    def GetSubList(self): ...

class HLIHeadingRegisterdTypeLibs(HLICOM):
    def GetText(self): ...
    def GetSubList(self): ...

def main(modal: bool = ...) -> None: ...
