from typing import Any

def CounterDefinition(*args, **kwargs) -> Any: ...
def LoadPerfCounterTextStrings(*args, **kwargs) -> Any: ...
def ObjectType(*args, **kwargs) -> Any: ...
def PerfMonManager(*args, **kwargs) -> Any: ...
def UnloadPerfCounterTextStrings(*args, **kwargs) -> Any: ...
