from typing import Any

COINIT_APARTMENTTHREADED: int
COINIT_DISABLE_OLE1DDE: int
COINIT_MULTITHREADED: int
COINIT_SPEED_OVER_MEMORY: int
EVENTLOG_AUDIT_FAILURE: int
EVENTLOG_AUDIT_SUCCESS: int
EVENTLOG_ERROR_TYPE: int
EVENTLOG_INFORMATION_TYPE: int
EVENTLOG_WARNING_TYPE: int
PYS_SERVICE_STARTED: int
PYS_SERVICE_STARTING: int
PYS_SERVICE_STOPPED: int
PYS_SERVICE_STOPPING: int

class startup_error(Exception): ...

def CoInitializeEx(*args, **kwargs) -> Any: ...
def CoUninitialize(*args, **kwargs) -> Any: ...
def Debugging(*args, **kwargs) -> Any: ...
def Finalize(*args, **kwargs) -> Any: ...
def Initialize(*args, **kwargs) -> Any: ...
def LogErrorMsg(*args, **kwargs) -> Any: ...
def LogInfoMsg(*args, **kwargs) -> Any: ...
def LogMsg(*args, **kwargs) -> Any: ...
def LogWarningMsg(*args, **kwargs) -> Any: ...
def PrepareToHostMultiple(*args, **kwargs) -> Any: ...
def PrepareToHostSingle(*args, **kwargs) -> Any: ...
def PumpWaitingMessages(*args, **kwargs) -> Any: ...
def RegisterServiceCtrlHandler(*args, **kwargs) -> Any: ...
def RunningAsService(*args, **kwargs) -> Any: ...
def SetEventSourceName(*args, **kwargs) -> Any: ...
def StartServiceCtrlDispatcher(*args, **kwargs) -> Any: ...
