from _typeshed import Incomplete
from typing import Any
from typing_extensions import final

DBT_CONFIGCHANGECANCELED: int
DBT_CONFIGCHANGED: int
DBT_CUSTOMEVENT: int
DBT_DEVICEARRIVAL: int
DBT_DEVICEQUERYREMOVE: int
DBT_DEVICEQUERYREMOVEFAILED: int
DBT_DEVICEREMOVECOMPLETE: int
DBT_DEVICEREMOVEPENDING: int
DBT_DEVICETYPESPECIFIC: int
DBT_QUERYCHANGECONFIG: int
DF_ALLOWOTHERACCOUNTHOOK: int
SC_ACTION_NONE: int
SC_ACTION_REBOOT: int
SC_ACTION_RESTART: int
SC_ACTION_RUN_COMMAND: int
SC_ENUM_PROCESS_INFO: int
SC_GROUP_IDENTIFIER: int
SC_MANAGER_ALL_ACCESS: int
SC_MANAGER_CONNECT: int
SC_MANAGER_CREATE_SERVICE: int
SC_MANAGER_ENUMERATE_SERVICE: int
SC_MANAGER_LOCK: int
SC_MANAGER_MODIFY_BOOT_CONFIG: int
SC_MANAGER_QUERY_LOCK_STATUS: int
SERVICE_ACCEPT_HARDWAREPROFILECHANGE: int
SERVICE_ACCEPT_NETBINDCHANGE: int
SERVICE_ACCEPT_PARAMCHANGE: int
SERVICE_ACCEPT_PAUSE_CONTINUE: int
SERVICE_ACCEPT_POWEREVENT: int
SERVICE_ACCEPT_PRESHUTDOWN: int
SERVICE_ACCEPT_SESSIONCHANGE: int
SERVICE_ACCEPT_SHUTDOWN: int
SERVICE_ACCEPT_STOP: int
SERVICE_ACTIVE: int
SERVICE_ALL_ACCESS: int
SERVICE_AUTO_START: int
SERVICE_BOOT_START: int
SERVICE_CHANGE_CONFIG: int
SERVICE_CONFIG_DELAYED_AUTO_START_INFO: int
SERVICE_CONFIG_DESCRIPTION: int
SERVICE_CONFIG_FAILURE_ACTIONS: int
SERVICE_CONFIG_FAILURE_ACTIONS_FLAG: int
SERVICE_CONFIG_PRESHUTDOWN_INFO: int
SERVICE_CONFIG_REQUIRED_PRIVILEGES_INFO: int
SERVICE_CONFIG_SERVICE_SID_INFO: int
SERVICE_CONTINUE_PENDING: int
SERVICE_CONTROL_CONTINUE: int
SERVICE_CONTROL_DEVICEEVENT: int
SERVICE_CONTROL_HARDWAREPROFILECHANGE: int
SERVICE_CONTROL_INTERROGATE: int
SERVICE_CONTROL_NETBINDADD: int
SERVICE_CONTROL_NETBINDDISABLE: int
SERVICE_CONTROL_NETBINDENABLE: int
SERVICE_CONTROL_NETBINDREMOVE: int
SERVICE_CONTROL_PARAMCHANGE: int
SERVICE_CONTROL_PAUSE: int
SERVICE_CONTROL_POWEREVENT: int
SERVICE_CONTROL_PRESHUTDOWN: int
SERVICE_CONTROL_SESSIONCHANGE: int
SERVICE_CONTROL_SHUTDOWN: int
SERVICE_CONTROL_STOP: int
SERVICE_DEMAND_START: int
SERVICE_DISABLED: int
SERVICE_DRIVER: int
SERVICE_ENUMERATE_DEPENDENTS: int
SERVICE_ERROR_CRITICAL: int
SERVICE_ERROR_IGNORE: int
SERVICE_ERROR_NORMAL: int
SERVICE_ERROR_SEVERE: int
SERVICE_FILE_SYSTEM_DRIVER: int
SERVICE_INACTIVE: int
SERVICE_INTERACTIVE_PROCESS: int
SERVICE_INTERROGATE: int
SERVICE_KERNEL_DRIVER: int
SERVICE_NO_CHANGE: int
SERVICE_PAUSED: int
SERVICE_PAUSE_CONTINUE: int
SERVICE_PAUSE_PENDING: int
SERVICE_QUERY_CONFIG: int
SERVICE_QUERY_STATUS: int
SERVICE_RUNNING: int
SERVICE_SID_TYPE_NONE: int
SERVICE_SID_TYPE_RESTRICTED: int
SERVICE_SID_TYPE_UNRESTRICTED: int
SERVICE_SPECIFIC_ERROR: int
SERVICE_START: int
SERVICE_START_PENDING: int
SERVICE_STATE_ALL: int
SERVICE_STOP: int
SERVICE_STOPPED: int
SERVICE_STOP_PENDING: int
SERVICE_SYSTEM_START: int
SERVICE_USER_DEFINED_CONTROL: int
SERVICE_WIN32: int
SERVICE_WIN32_OWN_PROCESS: int
SERVICE_WIN32_SHARE_PROCESS: int
UNICODE: int
UOI_FLAGS: int
UOI_NAME: int
UOI_TYPE: int
UOI_USER_SID: int
WSF_VISIBLE: int

@final
class HDESKType:
    def __init__(self, *args, **kwargs) -> None: ...
    def CloseDesktop(self, *args, **kwargs) -> Any: ...
    def Detach(self, *args, **kwargs) -> Any: ...
    def EnumDesktopWindows(self, *args, **kwargs) -> Any: ...
    def SetThreadDesktop(self, *args, **kwargs) -> Any: ...
    def SwitchDesktop(self, *args, **kwargs) -> Any: ...
    def __abs__(self) -> Any: ...
    def __add__(self, other) -> Any: ...
    def __and__(self, other) -> Any: ...
    def __bool__(self) -> Any: ...
    def __delattr__(self, name) -> Any: ...
    def __divmod__(self, other) -> Any: ...
    def __float__(self) -> Any: ...
    def __int__(self) -> Any: ...
    def __invert__(self) -> Any: ...
    def __lshift__(self, other) -> Any: ...
    def __mod__(self, other) -> Any: ...
    def __mul__(self, other) -> Any: ...
    def __neg__(self) -> Any: ...
    def __or__(self, other) -> Any: ...
    def __pos__(self) -> Any: ...
    def __pow__(self, other, mod: Incomplete | None = ...) -> Any: ...
    def __radd__(self, other) -> Any: ...
    def __rand__(self, other) -> Any: ...
    def __rdivmod__(self, other) -> Any: ...
    def __rlshift__(self, other) -> Any: ...
    def __rmod__(self, other) -> Any: ...
    def __rmul__(self, other) -> Any: ...
    def __ror__(self, other) -> Any: ...
    def __rpow__(self, other, mod: Incomplete | None = ...) -> Any: ...
    def __rrshift__(self, other) -> Any: ...
    def __rshift__(self, other) -> Any: ...
    def __rsub__(self, other) -> Any: ...
    def __rxor__(self, other) -> Any: ...
    def __setattr__(self, name, value) -> Any: ...
    def __sub__(self, other) -> Any: ...
    def __xor__(self, other) -> Any: ...

@final
class HWINSTAType:
    def __init__(self, *args, **kwargs) -> None: ...
    def CloseWindowStation(self, *args, **kwargs) -> Any: ...
    def Detach(self, *args, **kwargs) -> Any: ...
    def EnumDesktops(self, *args, **kwargs) -> Any: ...
    def SetProcessWindowStation(self, *args, **kwargs) -> Any: ...
    def __abs__(self) -> Any: ...
    def __add__(self, other) -> Any: ...
    def __and__(self, other) -> Any: ...
    def __bool__(self) -> Any: ...
    def __delattr__(self, name) -> Any: ...
    def __divmod__(self, other) -> Any: ...
    def __float__(self) -> Any: ...
    def __int__(self) -> Any: ...
    def __invert__(self) -> Any: ...
    def __lshift__(self, other) -> Any: ...
    def __mod__(self, other) -> Any: ...
    def __mul__(self, other) -> Any: ...
    def __neg__(self) -> Any: ...
    def __or__(self, other) -> Any: ...
    def __pos__(self) -> Any: ...
    def __pow__(self, other, mod: Incomplete | None = ...) -> Any: ...
    def __radd__(self, other) -> Any: ...
    def __rand__(self, other) -> Any: ...
    def __rdivmod__(self, other) -> Any: ...
    def __rlshift__(self, other) -> Any: ...
    def __rmod__(self, other) -> Any: ...
    def __rmul__(self, other) -> Any: ...
    def __ror__(self, other) -> Any: ...
    def __rpow__(self, other, mod: Incomplete | None = ...) -> Any: ...
    def __rrshift__(self, other) -> Any: ...
    def __rshift__(self, other) -> Any: ...
    def __rsub__(self, other) -> Any: ...
    def __rxor__(self, other) -> Any: ...
    def __setattr__(self, name, value) -> Any: ...
    def __sub__(self, other) -> Any: ...
    def __xor__(self, other) -> Any: ...

class error(Exception): ...

def ChangeServiceConfig(*args, **kwargs) -> Any: ...
def ChangeServiceConfig2(*args, **kwargs) -> Any: ...
def CloseServiceHandle(*args, **kwargs) -> Any: ...
def ControlService(*args, **kwargs) -> Any: ...
def CreateDesktop(*args, **kwargs) -> Any: ...
def CreateService(*args, **kwargs) -> Any: ...
def CreateWindowStation(*args, **kwargs) -> Any: ...
def DeleteService(*args, **kwargs) -> Any: ...
def EnumDependentServices(*args, **kwargs) -> Any: ...
def EnumServicesStatus(*args, **kwargs) -> Any: ...
def EnumServicesStatusEx(*args, **kwargs) -> Any: ...
def EnumWindowStations(*args, **kwargs) -> Any: ...
def GetProcessWindowStation(*args, **kwargs) -> Any: ...
def GetServiceDisplayName(*args, **kwargs) -> Any: ...
def GetServiceKeyName(*args, **kwargs) -> Any: ...
def GetThreadDesktop(*args, **kwargs) -> Any: ...
def GetUserObjectInformation(*args, **kwargs) -> Any: ...
def LockServiceDatabase(*args, **kwargs) -> Any: ...
def OpenDesktop(*args, **kwargs) -> Any: ...
def OpenInputDesktop(*args, **kwargs) -> Any: ...
def OpenSCManager(*args, **kwargs) -> Any: ...
def OpenService(*args, **kwargs) -> Any: ...
def OpenWindowStation(*args, **kwargs) -> Any: ...
def QueryServiceConfig(*args, **kwargs) -> Any: ...
def QueryServiceConfig2(*args, **kwargs) -> Any: ...
def QueryServiceLockStatus(*args, **kwargs) -> Any: ...
def QueryServiceObjectSecurity(*args, **kwargs) -> Any: ...
def QueryServiceStatus(*args, **kwargs) -> Any: ...
def QueryServiceStatusEx(*args, **kwargs) -> Any: ...
def SetServiceObjectSecurity(*args, **kwargs) -> Any: ...
def SetServiceStatus(*args, **kwargs) -> Any: ...
def SetUserObjectInformation(*args, **kwargs) -> Any: ...
def StartService(*args, **kwargs) -> Any: ...
def UnlockServiceDatabase(*args, **kwargs) -> Any: ...
