from typing import Any

EVENT_ALL_ACCESS: int
EVENT_MODIFY_STATE: int
INFINITE: int
MAXIMUM_WAIT_OBJECTS: int
QS_ALLEVENTS: int
QS_ALLINPUT: int
QS_HOTKEY: int
QS_INPUT: int
QS_KEY: int
QS_MOUSE: int
QS_MOUSEBUTTON: int
QS_MOUSEMOVE: int
QS_PAINT: int
QS_POSTMESSAGE: int
QS_SENDMESSAGE: int
QS_TIMER: int
SYNCHRONIZE: int
UNICODE: int
WAIT_ABANDONED: int
WAIT_ABANDONED_0: int
WAIT_FAILED: int
WAIT_IO_COMPLETION: int
WAIT_OBJECT_0: int
WAIT_TIMEOUT: int

class error(Exception): ...

def CancelWaitableTimer(*args, **kwargs) -> Any: ...
def CreateEvent(*args, **kwargs) -> Any: ...
def CreateMutex(*args, **kwargs) -> Any: ...
def CreateSemaphore(*args, **kwargs) -> Any: ...
def CreateWaitableTimer(*args, **kwargs) -> Any: ...
def MsgWaitForMultipleObjects(*args, **kwargs) -> Any: ...
def MsgWaitForMultipleObjectsEx(*args, **kwargs) -> Any: ...
def OpenEvent(*args, **kwargs) -> Any: ...
def OpenMutex(*args, **kwargs) -> Any: ...
def OpenSemaphore(*args, **kwargs) -> Any: ...
def OpenWaitableTimer(*args, **kwargs) -> Any: ...
def PulseEvent(*args, **kwargs) -> Any: ...
def ReleaseMutex(*args, **kwargs) -> Any: ...
def ReleaseSemaphore(*args, **kwargs) -> Any: ...
def ResetEvent(*args, **kwargs) -> Any: ...
def SetEvent(*args, **kwargs) -> Any: ...
def SetWaitableTimer(*args, **kwargs) -> Any: ...
def SignalObjectAndWait(*args, **kwargs) -> Any: ...
def WaitForInputIdle(*args, **kwargs) -> Any: ...
def WaitForMultipleObjects(*args, **kwargs) -> Any: ...
def WaitForMultipleObjectsEx(*args, **kwargs) -> Any: ...
def WaitForSingleObject(*args, **kwargs) -> Any: ...
def WaitForSingleObjectEx(*args, **kwargs) -> Any: ...
