from typing import Any

NameCanonical: int
NameCanonicalEx: int
NameDisplay: int
NameFullyQualifiedDN: int
NameSamCompatible: int
NameServicePrincipal: int
NameUniqueId: int
NameUnknown: int
NameUserPrincipal: int
REG_NOTIFY_CHANGE_ATTRIBUTES: int
REG_NOTIFY_CHANGE_LAST_SET: int
REG_NOTIFY_CHANGE_NAME: int
REG_NOTIFY_CHANGE_SECURITY: int
STD_ERROR_HANDLE: int
STD_INPUT_HANDLE: int
STD_OUTPUT_HANDLE: int
VFT_APP: int
VFT_DLL: int
VFT_DRV: int
VFT_FONT: int
VFT_STATIC_LIB: int
VFT_UNKNOWN: int
VFT_VXD: int
VOS_DOS: int
VOS_DOS_WINDOWS16: int
VOS_DOS_WINDOWS32: int
VOS_NT: int
VOS_NT_WINDOWS32: int
VOS_OS216: int
VOS_OS216_PM16: int
VOS_OS232: int
VOS_OS232_PM32: int
VOS_UNKNOWN: int
VOS__PM16: int
VOS__PM32: int
VOS__WINDOWS16: int
VOS__WINDOWS32: int
VS_FF_DEBUG: int
VS_FF_INFOINFERRED: int
VS_FF_PATCHED: int
VS_FF_PRERELEASE: int
VS_FF_PRIVATEBUILD: int
VS_FF_SPECIALBUILD: int

class PyDISPLAY_DEVICEType:
    DeviceID: Any
    DeviceKey: Any
    DeviceName: Any
    DeviceString: Any
    Size: Any
    StateFlags: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def Clear(self, *args, **kwargs) -> Any: ...
    def __delattr__(self, name) -> Any: ...
    def __setattr__(self, name, value) -> Any: ...

class error(Exception): ...

def AbortSystemShutdown(*args, **kwargs) -> Any: ...
def Apply(*args, **kwargs) -> Any: ...
def Beep(*args, **kwargs) -> Any: ...
def BeginUpdateResource(*args, **kwargs) -> Any: ...
def ChangeDisplaySettings(*args, **kwargs) -> Any: ...
def ChangeDisplaySettingsEx(*args, **kwargs) -> Any: ...
def ClipCursor(*args, **kwargs) -> Any: ...
def CloseHandle(*args, **kwargs) -> Any: ...
def CommandLineToArgv(*args, **kwargs) -> Any: ...
def CopyFile(*args, **kwargs) -> Any: ...
def DebugBreak(*args, **kwargs) -> Any: ...
def DeleteFile(*args, **kwargs) -> Any: ...
def DragFinish(*args, **kwargs) -> Any: ...
def DragQueryFile(*args, **kwargs) -> Any: ...
def DuplicateHandle(*args, **kwargs) -> Any: ...
def EndUpdateResource(*args, **kwargs) -> Any: ...
def EnumDisplayDevices(*args, **kwargs) -> Any: ...
def EnumDisplayMonitors(*args, **kwargs) -> Any: ...
def EnumDisplaySettings(*args, **kwargs) -> Any: ...
def EnumDisplaySettingsEx(*args, **kwargs) -> Any: ...
def EnumResourceLanguages(*args, **kwargs) -> Any: ...
def EnumResourceNames(*args, **kwargs) -> Any: ...
def EnumResourceTypes(*args, **kwargs) -> Any: ...
def ExitWindows(*args, **kwargs) -> Any: ...
def ExitWindowsEx(*args, **kwargs) -> Any: ...
def ExpandEnvironmentStrings(*args, **kwargs) -> Any: ...
def FindCloseChangeNotification(*args, **kwargs) -> Any: ...
def FindExecutable(*args, **kwargs) -> Any: ...
def FindFiles(*args, **kwargs) -> Any: ...
def FindFirstChangeNotification(*args, **kwargs) -> Any: ...
def FindNextChangeNotification(*args, **kwargs) -> Any: ...
def FormatMessage(*args, **kwargs) -> Any: ...
def FormatMessageW(*args, **kwargs) -> Any: ...
def FreeLibrary(*args, **kwargs) -> Any: ...
def GenerateConsoleCtrlEvent(*args, **kwargs) -> Any: ...
def GetAsyncKeyState(*args, **kwargs) -> Any: ...
def GetCommandLine(*args, **kwargs) -> Any: ...
def GetComputerName(*args, **kwargs) -> Any: ...
def GetComputerNameEx(*args, **kwargs) -> Any: ...
def GetComputerObjectName(*args, **kwargs) -> Any: ...
def GetConsoleTitle(*args, **kwargs) -> Any: ...
def GetCurrentProcess(*args, **kwargs) -> Any: ...
def GetCurrentProcessId(*args, **kwargs) -> Any: ...
def GetCurrentThread(*args, **kwargs) -> Any: ...
def GetCurrentThreadId(*args, **kwargs) -> Any: ...
def GetCursorPos(*args, **kwargs) -> Any: ...
def GetDateFormat(*args, **kwargs) -> Any: ...
def GetDiskFreeSpace(*args, **kwargs) -> Any: ...
def GetDiskFreeSpaceEx(*args, **kwargs) -> Any: ...
def GetDllDirectory(*args, **kwargs) -> Any: ...
def GetDomainName(*args, **kwargs) -> Any: ...
def GetEnvironmentVariable(*args, **kwargs) -> Any: ...
def GetEnvironmentVariableW(*args, **kwargs) -> Any: ...
def GetFileAttributes(*args, **kwargs) -> Any: ...
def GetFileVersionInfo(*args, **kwargs) -> Any: ...
def GetFocus(*args, **kwargs) -> Any: ...
def GetFullPathName(*args, **kwargs) -> Any: ...
def GetHandleInformation(*args, **kwargs) -> Any: ...
def GetKeyState(*args, **kwargs) -> Any: ...
def GetKeyboardLayout(*args, **kwargs) -> Any: ...
def GetKeyboardLayoutList(*args, **kwargs) -> Any: ...
def GetKeyboardLayoutName(*args, **kwargs) -> Any: ...
def GetKeyboardState(*args, **kwargs) -> Any: ...
def GetLastError(*args, **kwargs) -> Any: ...
def GetLastInputInfo(*args, **kwargs) -> Any: ...
def GetLocalTime(*args, **kwargs) -> Any: ...
def GetLogicalDriveStrings(*args, **kwargs) -> Any: ...
def GetLogicalDrives(*args, **kwargs) -> Any: ...
def GetLongPathName(*args, **kwargs) -> Any: ...
def GetLongPathNameW(*args, **kwargs) -> Any: ...
def GetModuleFileName(*args, **kwargs) -> Any: ...
def GetModuleFileNameW(*args, **kwargs) -> Any: ...
def GetModuleHandle(*args, **kwargs) -> Any: ...
def GetMonitorInfo(*args, **kwargs) -> Any: ...
def GetNativeSystemInfo(*args, **kwargs) -> Any: ...
def GetProcAddress(*args, **kwargs) -> Any: ...
def GetProfileSection(*args, **kwargs) -> Any: ...
def GetProfileVal(*args, **kwargs) -> Any: ...
def GetPwrCapabilities(*args, **kwargs) -> Any: ...
def GetShortPathName(*args, **kwargs) -> Any: ...
def GetStdHandle(*args, **kwargs) -> Any: ...
def GetSysColor(*args, **kwargs) -> Any: ...
def GetSystemDefaultLCID(*args, **kwargs) -> Any: ...
def GetSystemDefaultLangID(*args, **kwargs) -> Any: ...
def GetSystemDirectory(*args, **kwargs) -> Any: ...
def GetSystemFileCacheSize(*args, **kwargs) -> Any: ...
def GetSystemInfo(*args, **kwargs) -> Any: ...
def GetSystemMetrics(*args, **kwargs) -> Any: ...
def GetSystemTime(*args, **kwargs) -> Any: ...
def GetTempFileName(*args, **kwargs) -> Any: ...
def GetTempPath(*args, **kwargs) -> Any: ...
def GetThreadLocale(*args, **kwargs) -> Any: ...
def GetTickCount(*args, **kwargs) -> Any: ...
def GetTimeFormat(*args, **kwargs) -> Any: ...
def GetTimeZoneInformation(*args, **kwargs) -> Any: ...
def GetUserDefaultLCID(*args, **kwargs) -> Any: ...
def GetUserDefaultLangID(*args, **kwargs) -> Any: ...
def GetUserName(*args, **kwargs) -> Any: ...
def GetUserNameEx(*args, **kwargs) -> Any: ...
def GetVersion(*args, **kwargs) -> Any: ...
def GetVersionEx(*args, **kwargs) -> Any: ...
def GetVolumeInformation(*args, **kwargs) -> Any: ...
def GetWindowLong(*args, **kwargs) -> Any: ...
def GetWindowsDirectory(*args, **kwargs) -> Any: ...
def GlobalMemoryStatus(*args, **kwargs) -> Any: ...
def GlobalMemoryStatusEx(*args, **kwargs) -> Any: ...
def HIBYTE(*args, **kwargs) -> Any: ...
def HIWORD(*args, **kwargs) -> Any: ...
def InitiateSystemShutdown(*args, **kwargs) -> Any: ...
def LOBYTE(*args, **kwargs) -> Any: ...
def LOWORD(*args, **kwargs) -> Any: ...
def LoadCursor(*args, **kwargs) -> Any: ...
def LoadKeyboardLayout(*args, **kwargs) -> Any: ...
def LoadLibrary(*args, **kwargs) -> Any: ...
def LoadLibraryEx(*args, **kwargs) -> Any: ...
def LoadResource(*args, **kwargs) -> Any: ...
def LoadString(*args, **kwargs) -> Any: ...
def MAKELANGID(*args, **kwargs) -> Any: ...
def MAKELONG(*args, **kwargs) -> Any: ...
def MAKEWORD(*args, **kwargs) -> Any: ...
def MapVirtualKey(*args, **kwargs) -> Any: ...
def MessageBeep(*args, **kwargs) -> Any: ...
def MessageBox(*args, **kwargs) -> Any: ...
def MessageBoxEx(*args, **kwargs) -> Any: ...
def MonitorFromPoint(*args, **kwargs) -> Any: ...
def MonitorFromRect(*args, **kwargs) -> Any: ...
def MonitorFromWindow(*args, **kwargs) -> Any: ...
def MoveFile(*args, **kwargs) -> Any: ...
def MoveFileEx(*args, **kwargs) -> Any: ...
def OpenProcess(*args, **kwargs) -> Any: ...
def OpenThread(*args, **kwargs) -> Any: ...
def OutputDebugString(*args, **kwargs) -> Any: ...
def PostMessage(*args, **kwargs) -> Any: ...
def PostQuitMessage(*args, **kwargs) -> Any: ...
def PostThreadMessage(*args, **kwargs) -> Any: ...
def RGB(*args, **kwargs) -> Any: ...
def RegCloseKey(*args, **kwargs) -> Any: ...
def RegConnectRegistry(*args, **kwargs) -> Any: ...
def RegCopyTree(*args, **kwargs) -> Any: ...
def RegCreateKey(*args, **kwargs) -> Any: ...
def RegCreateKeyEx(*args, **kwargs) -> Any: ...
def RegDeleteKey(*args, **kwargs) -> Any: ...
def RegDeleteKeyEx(*args, **kwargs) -> Any: ...
def RegDeleteTree(*args, **kwargs) -> Any: ...
def RegDeleteValue(*args, **kwargs) -> Any: ...
def RegEnumKey(*args, **kwargs) -> Any: ...
def RegEnumKeyEx(*args, **kwargs) -> Any: ...
def RegEnumKeyExW(*args, **kwargs) -> Any: ...
def RegEnumValue(*args, **kwargs) -> Any: ...
def RegFlushKey(*args, **kwargs) -> Any: ...
def RegGetKeySecurity(*args, **kwargs) -> Any: ...
def RegLoadKey(*args, **kwargs) -> Any: ...
def RegNotifyChangeKeyValue(*args, **kwargs) -> Any: ...
def RegOpenCurrentUser(*args, **kwargs) -> Any: ...
def RegOpenKey(*args, **kwargs) -> Any: ...
def RegOpenKeyEx(*args, **kwargs) -> Any: ...
def RegOpenKeyTransacted(*args, **kwargs) -> Any: ...
def RegOverridePredefKey(*args, **kwargs) -> Any: ...
def RegQueryInfoKey(*args, **kwargs) -> Any: ...
def RegQueryInfoKeyW(*args, **kwargs) -> Any: ...
def RegQueryValue(*args, **kwargs) -> Any: ...
def RegQueryValueEx(*args, **kwargs) -> Any: ...
def RegRestoreKey(*args, **kwargs) -> Any: ...
def RegSaveKey(*args, **kwargs) -> Any: ...
def RegSaveKeyEx(*args, **kwargs) -> Any: ...
def RegSetKeySecurity(*args, **kwargs) -> Any: ...
def RegSetValue(*args, **kwargs) -> Any: ...
def RegSetValueEx(*args, **kwargs) -> Any: ...
def RegUnLoadKey(*args, **kwargs) -> Any: ...
def RegisterWindowMessage(*args, **kwargs) -> Any: ...
def SearchPath(*args, **kwargs) -> Any: ...
def SendMessage(*args, **kwargs) -> Any: ...
def SetClassLong(*args, **kwargs) -> Any: ...
def SetClassWord(*args, **kwargs) -> Any: ...
def SetConsoleCtrlHandler(*args, **kwargs) -> Any: ...
def SetConsoleTitle(*args, **kwargs) -> Any: ...
def SetCursor(*args, **kwargs) -> Any: ...
def SetCursorPos(*args, **kwargs) -> Any: ...
def SetDllDirectory(*args, **kwargs) -> Any: ...
def SetEnvironmentVariable(*args, **kwargs) -> Any: ...
def SetEnvironmentVariableW(*args, **kwargs) -> Any: ...
def SetErrorMode(*args, **kwargs) -> Any: ...
def SetFileAttributes(*args, **kwargs) -> Any: ...
def SetHandleInformation(*args, **kwargs) -> Any: ...
def SetLastError(*args, **kwargs) -> Any: ...
def SetLocalTime(*args, **kwargs) -> Any: ...
def SetStdHandle(*args, **kwargs) -> Any: ...
def SetSysColors(*args, **kwargs) -> Any: ...
def SetSystemFileCacheSize(*args, **kwargs) -> Any: ...
def SetSystemPowerState(*args, **kwargs) -> Any: ...
def SetSystemTime(*args, **kwargs) -> Any: ...
def SetThreadLocale(*args, **kwargs) -> Any: ...
def SetTimeZoneInformation(*args, **kwargs) -> Any: ...
def SetWindowLong(*args, **kwargs) -> Any: ...
def ShellExecute(*args, **kwargs) -> Any: ...
def ShowCursor(*args, **kwargs) -> Any: ...
def Sleep(*args, **kwargs) -> Any: ...
def SleepEx(*args, **kwargs) -> Any: ...
def TerminateProcess(*args, **kwargs) -> Any: ...
def ToAsciiEx(*args, **kwargs) -> Any: ...
def Unicode(*args, **kwargs) -> Any: ...
def UpdateResource(*args, **kwargs) -> Any: ...
def VkKeyScan(*args, **kwargs) -> Any: ...
def VkKeyScanEx(*args, **kwargs) -> Any: ...
def WinExec(*args, **kwargs) -> Any: ...
def WinHelp(*args, **kwargs) -> Any: ...
def WriteProfileSection(*args, **kwargs) -> Any: ...
def WriteProfileVal(*args, **kwargs) -> Any: ...
def keybd_event(*args, **kwargs) -> Any: ...
def mouse_event(*args, **kwargs) -> Any: ...
