from typing import Any

ABOVE_NORMAL_PRIORITY_CLASS: int
BELOW_NORMAL_PRIORITY_CLASS: int
CREATE_BREAKAWAY_FROM_JOB: int
CREATE_DEFAULT_ERROR_MODE: int
CREATE_NEW_CONSOLE: int
CREATE_NEW_PROCESS_GROUP: int
CREATE_NO_WINDOW: int
CREATE_PRESERVE_CODE_AUTHZ_LEVEL: int
CREATE_SEPARATE_WOW_VDM: int
CREATE_SHARED_WOW_VDM: int
CREATE_SUSPENDED: int
CREATE_UNICODE_ENVIRONMENT: int
DEBUG_ONLY_THIS_PROCESS: int
DEBUG_PROCESS: int
DETACHED_PROCESS: int
HIGH_PRIORITY_CLASS: int
IDLE_PRIORITY_CLASS: int
LIST_MODULES_32BIT: int
LIST_MODULES_64BIT: int
LIST_MODULES_ALL: int
LIST_MODULES_DEFAULT: int
MAXIMUM_PROCESSORS: int
NORMAL_PRIORITY_CLASS: int
REALTIME_PRIORITY_CLASS: int
STARTF_FORCEOFFFEEDBACK: int
STARTF_FORCEONFEEDBACK: int
STARTF_RUNFULLSCREEN: int
STARTF_USECOUNTCHARS: int
STARTF_USEFILLATTRIBUTE: int
STARTF_USEPOSITION: int
STARTF_USESHOWWINDOW: int
STARTF_USESIZE: int
STARTF_USESTDHANDLES: int
THREAD_MODE_BACKGROUND_BEGIN: int
THREAD_MODE_BACKGROUND_END: int
THREAD_PRIORITY_ABOVE_NORMAL: int
THREAD_PRIORITY_BELOW_NORMAL: int
THREAD_PRIORITY_HIGHEST: int
THREAD_PRIORITY_IDLE: int
THREAD_PRIORITY_LOWEST: int
THREAD_PRIORITY_NORMAL: int
THREAD_PRIORITY_TIME_CRITICAL: int
UNICODE: int

class error(Exception): ...

def AttachThreadInput(*args, **kwargs) -> Any: ...
def CreateProcess(*args, **kwargs) -> Any: ...
def CreateProcessAsUser(*args, **kwargs) -> Any: ...
def CreateRemoteThread(*args, **kwargs) -> Any: ...
def EnumProcessModules(*args, **kwargs) -> Any: ...
def EnumProcessModulesEx(*args, **kwargs) -> Any: ...
def EnumProcesses(*args, **kwargs) -> Any: ...
def ExitProcess(*args, **kwargs) -> Any: ...
def GetCurrentProcess(*args, **kwargs) -> Any: ...
def GetCurrentProcessId(*args, **kwargs) -> Any: ...
def GetExitCodeProcess(*args, **kwargs) -> Any: ...
def GetExitCodeThread(*args, **kwargs) -> Any: ...
def GetGuiResources(*args, **kwargs) -> Any: ...
def GetModuleFileNameEx(*args, **kwargs) -> Any: ...
def GetPriorityClass(*args, **kwargs) -> Any: ...
def GetProcessAffinityMask(*args, **kwargs) -> Any: ...
def GetProcessId(*args, **kwargs) -> Any: ...
def GetProcessIoCounters(*args, **kwargs) -> Any: ...
def GetProcessMemoryInfo(*args, **kwargs) -> Any: ...
def GetProcessPriorityBoost(*args, **kwargs) -> Any: ...
def GetProcessShutdownParameters(*args, **kwargs) -> Any: ...
def GetProcessTimes(*args, **kwargs) -> Any: ...
def GetProcessVersion(*args, **kwargs) -> Any: ...
def GetProcessWindowStation(*args, **kwargs) -> Any: ...
def GetProcessWorkingSetSize(*args, **kwargs) -> Any: ...
def GetStartupInfo(*args, **kwargs) -> Any: ...
def GetThreadIOPendingFlag(*args, **kwargs) -> Any: ...
def GetThreadPriority(*args, **kwargs) -> Any: ...
def GetThreadPriorityBoost(*args, **kwargs) -> Any: ...
def GetThreadTimes(*args, **kwargs) -> Any: ...
def GetWindowThreadProcessId(*args, **kwargs) -> Any: ...
def IsWow64Process(*args, **kwargs) -> Any: ...
def ReadProcessMemory(*args, **kwargs) -> Any: ...
def ResumeThread(*args, **kwargs) -> Any: ...
def STARTUPINFO(*args, **kwargs) -> Any: ...
def SetPriorityClass(*args, **kwargs) -> Any: ...
def SetProcessAffinityMask(*args, **kwargs) -> Any: ...
def SetProcessPriorityBoost(*args, **kwargs) -> Any: ...
def SetProcessShutdownParameters(*args, **kwargs) -> Any: ...
def SetProcessWorkingSetSize(*args, **kwargs) -> Any: ...
def SetThreadAffinityMask(*args, **kwargs) -> Any: ...
def SetThreadIdealProcessor(*args, **kwargs) -> Any: ...
def SetThreadPriority(*args, **kwargs) -> Any: ...
def SetThreadPriorityBoost(*args, **kwargs) -> Any: ...
def SuspendThread(*args, **kwargs) -> Any: ...
def TerminateProcess(*args, **kwargs) -> Any: ...
def VirtualAllocEx(*args, **kwargs) -> Any: ...
def VirtualFreeEx(*args, **kwargs) -> Any: ...
def WriteProcessMemory(*args, **kwargs) -> Any: ...
def beginthreadex(*args, **kwargs) -> Any: ...
