from typing import Any

PI_APPLYPOLICY: int
PI_NOUI: int
PT_MANDATORY: int
PT_ROAMING: int
PT_TEMPORARY: int

def CreateEnvironmentBlock(*args, **kwargs) -> Any: ...
def DeleteProfile(*args, **kwargs) -> Any: ...
def ExpandEnvironmentStringsForUser(*args, **kwargs) -> Any: ...
def GetAllUsersProfileDirectory(*args, **kwargs) -> Any: ...
def GetDefaultUserProfileDirectory(*args, **kwargs) -> Any: ...
def GetEnvironmentStrings(*args, **kwargs) -> Any: ...
def GetProfileType(*args, **kwargs) -> Any: ...
def GetProfilesDirectory(*args, **kwargs) -> Any: ...
def GetUserProfileDirectory(*args, **kwargs) -> Any: ...
def LoadUserProfile(*args, **kwargs) -> Any: ...
def UnloadUserProfile(*args, **kwargs) -> Any: ...
