from typing import Any

CALLBACK_CHUNK_FINISHED: int
CALLBACK_STREAM_SWITCH: int
CBR_110: int
CBR_115200: int
CBR_1200: int
CBR_128000: int
CBR_14400: int
CBR_19200: int
CBR_2400: int
CBR_256000: int
CBR_300: int
CBR_38400: int
CBR_4800: int
CBR_56000: int
CBR_57600: int
CBR_600: int
CBR_9600: int
CLRBREAK: int
CLRDTR: int
CLRRTS: int
COPY_FILE_ALLOW_DECRYPTED_DESTINATION: int
COPY_FILE_FAIL_IF_EXISTS: int
COPY_FILE_OPEN_SOURCE_FOR_WRITE: int
COPY_FILE_RESTARTABLE: int
CREATE_ALWAYS: int
CREATE_FOR_DIR: int
CREATE_FOR_IMPORT: int
CREATE_NEW: int
DRIVE_CDROM: int
DRIVE_FIXED: int
DRIVE_NO_ROOT_DIR: int
DRIVE_RAMDISK: int
DRIVE_REMOTE: int
DRIVE_REMOVABLE: int
DRIVE_UNKNOWN: int
DTR_CONTROL_DISABLE: int
DTR_CONTROL_ENABLE: int
DTR_CONTROL_HANDSHAKE: int
EVENPARITY: int
EV_BREAK: int
EV_CTS: int
EV_DSR: int
EV_ERR: int
EV_RING: int
EV_RLSD: int
EV_RXCHAR: int
EV_RXFLAG: int
EV_TXEMPTY: int
FD_ACCEPT: int
FD_ADDRESS_LIST_CHANGE: int
FD_CLOSE: int
FD_CONNECT: int
FD_GROUP_QOS: int
FD_OOB: int
FD_QOS: int
FD_READ: int
FD_ROUTING_INTERFACE_CHANGE: int
FD_WRITE: int
FILE_ALL_ACCESS: int
FILE_ATTRIBUTE_ARCHIVE: int
FILE_ATTRIBUTE_COMPRESSED: int
FILE_ATTRIBUTE_DIRECTORY: int
FILE_ATTRIBUTE_HIDDEN: int
FILE_ATTRIBUTE_NORMAL: int
FILE_ATTRIBUTE_OFFLINE: int
FILE_ATTRIBUTE_READONLY: int
FILE_ATTRIBUTE_SYSTEM: int
FILE_ATTRIBUTE_TEMPORARY: int
FILE_BEGIN: int
FILE_CURRENT: int
FILE_ENCRYPTABLE: int
FILE_END: int
FILE_FLAG_BACKUP_SEMANTICS: int
FILE_FLAG_DELETE_ON_CLOSE: int
FILE_FLAG_NO_BUFFERING: int
FILE_FLAG_OPEN_REPARSE_POINT: int
FILE_FLAG_OVERLAPPED: int
FILE_FLAG_POSIX_SEMANTICS: int
FILE_FLAG_RANDOM_ACCESS: int
FILE_FLAG_SEQUENTIAL_SCAN: int
FILE_FLAG_WRITE_THROUGH: int
FILE_GENERIC_READ: int
FILE_GENERIC_WRITE: int
FILE_IS_ENCRYPTED: int
FILE_READ_ONLY: int
FILE_ROOT_DIR: int
FILE_SHARE_DELETE: int
FILE_SHARE_READ: int
FILE_SHARE_WRITE: int
FILE_SYSTEM_ATTR: int
FILE_SYSTEM_DIR: int
FILE_SYSTEM_NOT_SUPPORT: int
FILE_TYPE_CHAR: int
FILE_TYPE_DISK: int
FILE_TYPE_PIPE: int
FILE_TYPE_UNKNOWN: int
FILE_UNKNOWN: int
FILE_USER_DISALLOWED: int
FileAllocationInfo: int
FileAttributeTagInfo: int
FileBasicInfo: int
FileCompressionInfo: int
FileDispositionInfo: int
FileEndOfFileInfo: int
FileIdBothDirectoryInfo: int
FileIdBothDirectoryRestartInfo: int
FileIdType: int
FileIoPriorityHintInfo: int
FileNameInfo: int
FileRenameInfo: int
FileStandardInfo: int
FileStreamInfo: int
GENERIC_EXECUTE: int
GENERIC_READ: int
GENERIC_WRITE: int
GetFileExInfoStandard: int
INVALID_HANDLE_VALUE: int
IoPriorityHintLow: int
IoPriorityHintNormal: int
IoPriorityHintVeryLow: int
MARKPARITY: int
MOVEFILE_COPY_ALLOWED: int
MOVEFILE_CREATE_HARDLINK: int
MOVEFILE_DELAY_UNTIL_REBOOT: int
MOVEFILE_FAIL_IF_NOT_TRACKABLE: int
MOVEFILE_REPLACE_EXISTING: int
MOVEFILE_WRITE_THROUGH: int
NOPARITY: int
ODDPARITY: int
ONE5STOPBITS: int
ONESTOPBIT: int
OPEN_ALWAYS: int
OPEN_EXISTING: int
OVERWRITE_HIDDEN: int
ObjectIdType: int
PROGRESS_CANCEL: int
PROGRESS_CONTINUE: int
PROGRESS_QUIET: int
PROGRESS_STOP: int
PURGE_RXABORT: int
PURGE_RXCLEAR: int
PURGE_TXABORT: int
PURGE_TXCLEAR: int
REPLACEFILE_IGNORE_MERGE_ERRORS: int
REPLACEFILE_WRITE_THROUGH: int
RTS_CONTROL_DISABLE: int
RTS_CONTROL_ENABLE: int
RTS_CONTROL_HANDSHAKE: int
RTS_CONTROL_TOGGLE: int
SCS_32BIT_BINARY: int
SCS_DOS_BINARY: int
SCS_OS216_BINARY: int
SCS_PIF_BINARY: int
SCS_POSIX_BINARY: int
SCS_WOW_BINARY: int
SECURITY_ANONYMOUS: int
SECURITY_CONTEXT_TRACKING: int
SECURITY_DELEGATION: int
SECURITY_EFFECTIVE_ONLY: int
SECURITY_IDENTIFICATION: int
SECURITY_IMPERSONATION: int
SETBREAK: int
SETDTR: int
SETRTS: int
SETXOFF: int
SETXON: int
SO_CONNECT_TIME: int
SO_UPDATE_ACCEPT_CONTEXT: int
SO_UPDATE_CONNECT_CONTEXT: int
SPACEPARITY: int
SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE: int
SYMBOLIC_LINK_FLAG_DIRECTORY: int
TF_DISCONNECT: int
TF_REUSE_SOCKET: int
TF_USE_DEFAULT_WORKER: int
TF_USE_KERNEL_APC: int
TF_USE_SYSTEM_THREAD: int
TF_WRITE_BEHIND: int
TRUNCATE_EXISTING: int
TWOSTOPBITS: int
UNICODE: int
WSAECONNABORTED: int
WSAECONNRESET: int
WSAEDISCON: int
WSAEFAULT: int
WSAEINPROGRESS: int
WSAEINTR: int
WSAEINVAL: int
WSAEMSGSIZE: int
WSAENETDOWN: int
WSAENETRESET: int
WSAENOBUFS: int
WSAENOTCONN: int
WSAENOTSOCK: int
WSAEOPNOTSUPP: int
WSAESHUTDOWN: int
WSAEWOULDBLOCK: int
WSA_IO_PENDING: int
WSA_OPERATION_ABORTED: int

class error(Exception): ...

def AcceptEx(*args, **kwargs) -> Any: ...
def AddUsersToEncryptedFile(*args, **kwargs) -> Any: ...
def AllocateReadBuffer(*args, **kwargs) -> Any: ...
def AreFileApisANSI(*args, **kwargs) -> Any: ...
def BackupRead(*args, **kwargs) -> Any: ...
def BackupSeek(*args, **kwargs) -> Any: ...
def BackupWrite(*args, **kwargs) -> Any: ...
def BuildCommDCB(*args, **kwargs) -> Any: ...
def CalculateSocketEndPointSize(*args, **kwargs) -> Any: ...
def CancelIo(*args, **kwargs) -> Any: ...
def ClearCommBreak(*args, **kwargs) -> Any: ...
def ClearCommError(*args, **kwargs) -> Any: ...
def CloseEncryptedFileRaw(*args, **kwargs) -> Any: ...
def CloseHandle(*args, **kwargs) -> Any: ...
def ConnectEx(*args, **kwargs) -> Any: ...
def CopyFile(*args, **kwargs) -> Any: ...
def CopyFileEx(*args, **kwargs) -> Any: ...
def CopyFileW(*args, **kwargs) -> Any: ...
def CreateDirectory(*args, **kwargs) -> Any: ...
def CreateDirectoryEx(*args, **kwargs) -> Any: ...
def CreateDirectoryExW(*args, **kwargs) -> Any: ...
def CreateDirectoryW(*args, **kwargs) -> Any: ...
def CreateFile(*args, **kwargs) -> Any: ...
def CreateFileW(*args, **kwargs) -> Any: ...
def CreateHardLink(*args, **kwargs) -> Any: ...
def CreateIoCompletionPort(*args, **kwargs) -> Any: ...
def CreateMailslot(*args, **kwargs) -> Any: ...
def CreateSymbolicLink(*args, **kwargs) -> Any: ...
def DCB(*args, **kwargs) -> Any: ...
def DecryptFile(*args, **kwargs) -> Any: ...
def DefineDosDevice(*args, **kwargs) -> Any: ...
def DefineDosDeviceW(*args, **kwargs) -> Any: ...
def DeleteFile(*args, **kwargs) -> Any: ...
def DeleteFileW(*args, **kwargs) -> Any: ...
def DeleteVolumeMountPoint(*args, **kwargs) -> Any: ...
def DeviceIoControl(*args, **kwargs) -> Any: ...
def DuplicateEncryptionInfoFile(*args, **kwargs) -> Any: ...
def EncryptFile(*args, **kwargs) -> Any: ...
def EncryptionDisable(*args, **kwargs) -> Any: ...
def EscapeCommFunction(*args, **kwargs) -> Any: ...
def FILE_NOTIFY_INFORMATION(*args, **kwargs) -> Any: ...
def FileEncryptionStatus(*args, **kwargs) -> Any: ...
def FindClose(*args, **kwargs) -> Any: ...
def FindCloseChangeNotification(*args, **kwargs) -> Any: ...
def FindFileNames(*args, **kwargs) -> Any: ...
def FindFilesIterator(*args, **kwargs) -> Any: ...
def FindFilesW(*args, **kwargs) -> Any: ...
def FindFirstChangeNotification(*args, **kwargs) -> Any: ...
def FindNextChangeNotification(*args, **kwargs) -> Any: ...
def FindStreams(*args, **kwargs) -> Any: ...
def FlushFileBuffers(*args, **kwargs) -> Any: ...
def GetAcceptExSockaddrs(*args, **kwargs) -> Any: ...
def GetBinaryType(*args, **kwargs) -> Any: ...
def GetCommMask(*args, **kwargs) -> Any: ...
def GetCommModemStatus(*args, **kwargs) -> Any: ...
def GetCommState(*args, **kwargs) -> Any: ...
def GetCommTimeouts(*args, **kwargs) -> Any: ...
def GetCompressedFileSize(*args, **kwargs) -> Any: ...
def GetDiskFreeSpace(*args, **kwargs) -> Any: ...
def GetDiskFreeSpaceEx(*args, **kwargs) -> Any: ...
def GetDriveType(*args, **kwargs) -> Any: ...
def GetDriveTypeW(*args, **kwargs) -> Any: ...
def GetFileAttributes(*args, **kwargs) -> Any: ...
def GetFileAttributesEx(*args, **kwargs) -> Any: ...
def GetFileAttributesExW(*args, **kwargs) -> Any: ...
def GetFileAttributesW(*args, **kwargs) -> Any: ...
def GetFileInformationByHandle(*args, **kwargs) -> Any: ...
def GetFileInformationByHandleEx(*args, **kwargs) -> Any: ...
def GetFileSize(*args, **kwargs) -> Any: ...
def GetFileTime(*args, **kwargs) -> Any: ...
def GetFileType(*args, **kwargs) -> Any: ...
def GetFinalPathNameByHandle(*args, **kwargs) -> Any: ...
def GetFullPathName(*args, **kwargs) -> Any: ...
def GetLogicalDrives(*args, **kwargs) -> Any: ...
def GetLongPathName(*args, **kwargs) -> Any: ...
def GetMailslotInfo(*args, **kwargs) -> Any: ...
def GetOverlappedResult(*args, **kwargs) -> Any: ...
def GetQueuedCompletionStatus(*args, **kwargs) -> Any: ...
def GetVolumeNameForVolumeMountPoint(*args, **kwargs) -> Any: ...
def GetVolumePathName(*args, **kwargs) -> Any: ...
def GetVolumePathNamesForVolumeName(*args, **kwargs) -> Any: ...
def LockFile(*args, **kwargs) -> Any: ...
def LockFileEx(*args, **kwargs) -> Any: ...
def MoveFile(*args, **kwargs) -> Any: ...
def MoveFileEx(*args, **kwargs) -> Any: ...
def MoveFileExW(*args, **kwargs) -> Any: ...
def MoveFileW(*args, **kwargs) -> Any: ...
def MoveFileWithProgress(*args, **kwargs) -> Any: ...
def OVERLAPPED(*args, **kwargs) -> Any: ...
def OpenEncryptedFileRaw(*args, **kwargs) -> Any: ...
def OpenFileById(*args, **kwargs) -> Any: ...
def PostQueuedCompletionStatus(*args, **kwargs) -> Any: ...
def PurgeComm(*args, **kwargs) -> Any: ...
def QueryDosDevice(*args, **kwargs) -> Any: ...
def QueryRecoveryAgentsOnEncryptedFile(*args, **kwargs) -> Any: ...
def QueryUsersOnEncryptedFile(*args, **kwargs) -> Any: ...
def ReOpenFile(*args, **kwargs) -> Any: ...
def ReadDirectoryChangesW(*args, **kwargs) -> Any: ...
def ReadEncryptedFileRaw(*args, **kwargs) -> Any: ...
def ReadFile(*args, **kwargs) -> Any: ...
def RemoveDirectory(*args, **kwargs) -> Any: ...
def RemoveUsersFromEncryptedFile(*args, **kwargs) -> Any: ...
def ReplaceFile(*args, **kwargs) -> Any: ...
def SetCommBreak(*args, **kwargs) -> Any: ...
def SetCommMask(*args, **kwargs) -> Any: ...
def SetCommState(*args, **kwargs) -> Any: ...
def SetCommTimeouts(*args, **kwargs) -> Any: ...
def SetCurrentDirectory(*args, **kwargs) -> Any: ...
def SetEndOfFile(*args, **kwargs) -> Any: ...
def SetFileApisToANSI(*args, **kwargs) -> Any: ...
def SetFileApisToOEM(*args, **kwargs) -> Any: ...
def SetFileAttributes(*args, **kwargs) -> Any: ...
def SetFileAttributesW(*args, **kwargs) -> Any: ...
def SetFileInformationByHandle(*args, **kwargs) -> Any: ...
def SetFilePointer(*args, **kwargs) -> Any: ...
def SetFileShortName(*args, **kwargs) -> Any: ...
def SetFileTime(*args, **kwargs) -> Any: ...
def SetMailslotInfo(*args, **kwargs) -> Any: ...
def SetVolumeLabel(*args, **kwargs) -> Any: ...
def SetVolumeMountPoint(*args, **kwargs) -> Any: ...
def SetupComm(*args, **kwargs) -> Any: ...
def SfcGetNextProtectedFile(*args, **kwargs) -> Any: ...
def SfcIsFileProtected(*args, **kwargs) -> Any: ...
def TransmitCommChar(*args, **kwargs) -> Any: ...
def TransmitFile(*args, **kwargs) -> Any: ...
def UnlockFile(*args, **kwargs) -> Any: ...
def UnlockFileEx(*args, **kwargs) -> Any: ...
def WSAAsyncSelect(*args, **kwargs) -> Any: ...
def WSAEnumNetworkEvents(*args, **kwargs) -> Any: ...
def WSAEventSelect(*args, **kwargs) -> Any: ...
def WSARecv(*args, **kwargs) -> Any: ...
def WSASend(*args, **kwargs) -> Any: ...
def WaitCommEvent(*args, **kwargs) -> Any: ...
def Wow64DisableWow64FsRedirection(*args, **kwargs) -> Any: ...
def Wow64RevertWow64FsRedirection(*args, **kwargs) -> Any: ...
def WriteEncryptedFileRaw(*args, **kwargs) -> Any: ...
def WriteFile(*args, **kwargs) -> Any: ...
