from typing import Any

CF_BITMAP: int
CF_DIB: int
CF_DIBV5: int
CF_DIF: int
CF_DSPBITMAP: int
CF_DSPENHMETAFILE: int
CF_DSPMETAFILEPICT: int
CF_DSPTEXT: int
CF_ENHMETAFILE: int
CF_HDROP: int
CF_LOCALE: int
CF_MAX: int
CF_METAFILEPICT: int
CF_OEMTEXT: int
CF_OWNERDISPLAY: int
CF_PALETTE: int
CF_PENDATA: int
CF_RIFF: int
CF_SYLK: int
CF_TEXT: int
CF_TIFF: int
CF_UNICODETEXT: int
CF_WAVE: int
UNICODE: bool

class error(Exception): ...

def ChangeClipboardChain(*args, **kwargs) -> Any: ...
def CloseClipboard(*args, **kwargs) -> Any: ...
def CountClipboardFormats(*args, **kwargs) -> Any: ...
def EmptyClipboard(*args, **kwargs) -> Any: ...
def EnumClipboardFormats(*args, **kwargs) -> Any: ...
def GetClipboardData(*args, **kwargs) -> Any: ...
def GetClipboardDataHandle(*args, **kwargs) -> Any: ...
def GetClipboardFormatName(*args, **kwargs) -> Any: ...
def GetClipboardOwner(*args, **kwargs) -> Any: ...
def GetClipboardSequenceNumber(*args, **kwargs) -> Any: ...
def GetClipboardViewer(*args, **kwargs) -> Any: ...
def GetGlobalMemory(*args, **kwargs) -> Any: ...
def GetOpenClipboardWindow(*args, **kwargs) -> Any: ...
def GetPriorityClipboardFormat(*args, **kwargs) -> Any: ...
def IsClipboardFormatAvailable(*args, **kwargs) -> Any: ...
def OpenClipboard(*args, **kwargs) -> Any: ...
def RegisterClipboardFormat(*args, **kwargs) -> Any: ...
def SetClipboardData(*args, **kwargs) -> Any: ...
def SetClipboardText(*args, **kwargs) -> Any: ...
def SetClipboardViewer(*args, **kwargs) -> Any: ...
