from win32.lib.pywintypes import IIDType, SECURITY_ATTRIBUTESType, error as error

def CreateTransaction(
    TransactionAttributes: SECURITY_ATTRIBUTESType | None = ...,
    UOW: IIDType | None = ...,
    CreateOptions: int = ...,
    IsolationLevel: int = ...,
    IsolationFlags: int = ...,
    Timeout: int = ...,
    Description: str | None = ...,
) -> int: ...
def RollbackTransaction(TransactionHandle: int) -> None: ...
def RollbackTransactionAsync(TransactionHandle: int) -> None: ...
def CommitTransaction(TransactionHandle: int) -> None: ...
def CommitTransactionAsync(TransactionHandle: int) -> None: ...
def GetTransactionId(TransactionHandle: int) -> IIDType: ...
def OpenTransaction(DesiredAccess, TransactionId: IIDType) -> int: ...
