from typing import Any

class error(Exception): ...

def CommitTransaction(*args, **kwargs) -> Any: ...
def CommitTransactionAsync(*args, **kwargs) -> Any: ...
def CreateTransaction(*args, **kwargs) -> Any: ...
def GetTransactionId(*args, **kwargs) -> Any: ...
def OpenTransaction(*args, **kwargs) -> Any: ...
def RollbackTransaction(*args, **kwargs) -> Any: ...
def RollbackTransactionAsync(*args, **kwargs) -> Any: ...
