from typing import Any

class error(Exception): ...

def GetHandle(*args, **kwargs) -> Any: ...
def GetTracer(*args, **kwargs) -> Any: ...
def InitRead(*args, **kwargs) -> Any: ...
def InitWrite(*args, **kwargs) -> Any: ...
def TermRead(*args, **kwargs) -> Any: ...
def TermWrite(*args, **kwargs) -> Any: ...
def blockingread(*args, **kwargs) -> Any: ...
def flush(*args, **kwargs) -> Any: ...
def read(*args, **kwargs) -> Any: ...
def setprint(*args, **kwargs) -> Any: ...
def write(*args, **kwargs) -> Any: ...
