from typing import Any

CLR_NONE: int
ILC_COLOR: int
ILC_COLOR16: int
ILC_COLOR24: int
ILC_COLOR32: int
ILC_COLOR4: int
ILC_COLOR8: int
ILC_COLORDDB: int
ILC_MASK: int
ILD_BLEND: int
ILD_BLEND25: int
ILD_BLEND50: int
ILD_FOCUS: int
ILD_MASK: int
ILD_NORMAL: int
ILD_SELECTED: int
ILD_TRANSPARENT: int
IMAGE_BITMAP: int
IMAGE_CURSOR: int
IMAGE_ICON: int
LR_CREATEDIBSECTION: int
LR_DEFAULTCOLOR: int
LR_DEFAULTSIZE: int
LR_LOADFROMFILE: int
LR_LOADMAP3DCOLORS: int
LR_LOADTRANSPARENT: int
LR_MONOCHROME: int
LR_SHARED: int
LR_VGACOLOR: int
NIF_ICON: int
NIF_INFO: int
NIF_MESSAGE: int
NIF_STATE: int
NIF_TIP: int
NIIF_ERROR: int
NIIF_ICON_MASK: int
NIIF_INFO: int
NIIF_NONE: int
NIIF_NOSOUND: int
NIIF_WARNING: int
NIM_ADD: int
NIM_DELETE: int
NIM_MODIFY: int
NIM_SETVERSION: int
TPM_BOTTOMALIGN: int
TPM_CENTERALIGN: int
TPM_LEFTALIGN: int
TPM_LEFTBUTTON: int
TPM_NONOTIFY: int
TPM_RETURNCMD: int
TPM_RIGHTALIGN: int
TPM_RIGHTBUTTON: int
TPM_TOPALIGN: int
TPM_VCENTERALIGN: int
UNICODE: bool
dllhandle: int

class error(Exception): ...

def AbortPath(*args, **kwargs) -> Any: ...
def AlphaBlend(*args, **kwargs) -> Any: ...
def AngleArc(*args, **kwargs) -> Any: ...
def AnimateWindow(*args, **kwargs) -> Any: ...
def AppendMenu(*args, **kwargs) -> Any: ...
def Arc(*args, **kwargs) -> Any: ...
def ArcTo(*args, **kwargs) -> Any: ...
def BeginPaint(*args, **kwargs) -> Any: ...
def BeginPath(*args, **kwargs) -> Any: ...
def BitBlt(*args, **kwargs) -> Any: ...
def BringWindowToTop(*args, **kwargs) -> Any: ...
def CallWindowProc(*args, **kwargs) -> Any: ...
def CheckMenuItem(*args, **kwargs) -> Any: ...
def CheckMenuRadioItem(*args, **kwargs) -> Any: ...
def ChildWindowFromPoint(*args, **kwargs) -> Any: ...
def ChildWindowFromPointEx(*args, **kwargs) -> Any: ...
def Chord(*args, **kwargs) -> Any: ...
def ClientToScreen(*args, **kwargs) -> Any: ...
def CloseFigure(*args, **kwargs) -> Any: ...
def CloseWindow(*args, **kwargs) -> Any: ...
def CombineRgn(*args, **kwargs) -> Any: ...
def CombineTransform(*args, **kwargs) -> Any: ...
def CommDlgExtendedError(*args, **kwargs) -> Any: ...
def CopyIcon(*args, **kwargs) -> Any: ...
def CreateAcceleratorTable(*args, **kwargs) -> Any: ...
def CreateBitmap(*args, **kwargs) -> Any: ...
def CreateBrushIndirect(*args, **kwargs) -> Any: ...
def CreateCaret(*args, **kwargs) -> Any: ...
def CreateCompatibleBitmap(*args, **kwargs) -> Any: ...
def CreateCompatibleDC(*args, **kwargs) -> Any: ...
def CreateDC(*args, **kwargs) -> Any: ...
def CreateDialogIndirect(*args, **kwargs) -> Any: ...
def CreateDialogIndirectParam(*args, **kwargs) -> Any: ...
def CreateEllipticRgnIndirect(*args, **kwargs) -> Any: ...
def CreateFontIndirect(*args, **kwargs) -> Any: ...
def CreateHatchBrush(*args, **kwargs) -> Any: ...
def CreateIconFromResource(*args, **kwargs) -> Any: ...
def CreateIconIndirect(*args, **kwargs) -> Any: ...
def CreateMenu(*args, **kwargs) -> Any: ...
def CreatePatternBrush(*args, **kwargs) -> Any: ...
def CreatePen(*args, **kwargs) -> Any: ...
def CreatePolygonRgn(*args, **kwargs) -> Any: ...
def CreatePopupMenu(*args, **kwargs) -> Any: ...
def CreateRectRgnIndirect(*args, **kwargs) -> Any: ...
def CreateRoundRectRgn(*args, **kwargs) -> Any: ...
def CreateSolidBrush(*args, **kwargs) -> Any: ...
def CreateWindow(*args, **kwargs) -> Any: ...
def CreateWindowEx(*args, **kwargs) -> Any: ...
def DefWindowProc(*args, **kwargs) -> Any: ...
def DeleteDC(*args, **kwargs) -> Any: ...
def DeleteMenu(*args, **kwargs) -> Any: ...
def DeleteObject(*args, **kwargs) -> Any: ...
def DestroyAcceleratorTable(*args, **kwargs) -> Any: ...
def DestroyCaret(*args, **kwargs) -> Any: ...
def DestroyIcon(*args, **kwargs) -> Any: ...
def DestroyMenu(*args, **kwargs) -> Any: ...
def DestroyWindow(*args, **kwargs) -> Any: ...
def DialogBox(*args, **kwargs) -> Any: ...
def DialogBoxIndirect(*args, **kwargs) -> Any: ...
def DialogBoxIndirectParam(*args, **kwargs) -> Any: ...
def DialogBoxParam(*args, **kwargs) -> Any: ...
def DispatchMessage(*args, **kwargs) -> Any: ...
def DragAcceptFiles(*args, **kwargs) -> Any: ...
def DragDetect(*args, **kwargs) -> Any: ...
def DrawAnimatedRects(*args, **kwargs) -> Any: ...
def DrawEdge(*args, **kwargs) -> Any: ...
def DrawFocusRect(*args, **kwargs) -> Any: ...
def DrawIcon(*args, **kwargs) -> Any: ...
def DrawIconEx(*args, **kwargs) -> Any: ...
def DrawMenuBar(*args, **kwargs) -> Any: ...
def DrawText(*args, **kwargs) -> Any: ...
def DrawTextW(*args, **kwargs) -> Any: ...
def Edit_GetLine(*args, **kwargs) -> Any: ...
def Ellipse(*args, **kwargs) -> Any: ...
def EnableMenuItem(*args, **kwargs) -> Any: ...
def EnableWindow(*args, **kwargs) -> Any: ...
def EndDialog(*args, **kwargs) -> Any: ...
def EndPaint(*args, **kwargs) -> Any: ...
def EndPath(*args, **kwargs) -> Any: ...
def EnumChildWindows(*args, **kwargs) -> Any: ...
def EnumFontFamilies(*args, **kwargs) -> Any: ...
def EnumPropsEx(*args, **kwargs) -> Any: ...
def EnumThreadWindows(*args, **kwargs) -> Any: ...
def EnumWindows(*args, **kwargs) -> Any: ...
def EqualRgn(*args, **kwargs) -> Any: ...
def ExtCreatePen(*args, **kwargs) -> Any: ...
def ExtFloodFill(*args, **kwargs) -> Any: ...
def ExtTextOut(*args, **kwargs) -> Any: ...
def ExtractIcon(*args, **kwargs) -> Any: ...
def ExtractIconEx(*args, **kwargs) -> Any: ...
def FillPath(*args, **kwargs) -> Any: ...
def FillRect(*args, **kwargs) -> Any: ...
def FillRgn(*args, **kwargs) -> Any: ...
def FindWindow(*args, **kwargs) -> Any: ...
def FindWindowEx(*args, **kwargs) -> Any: ...
def FlashWindow(*args, **kwargs) -> Any: ...
def FlashWindowEx(*args, **kwargs) -> Any: ...
def FlattenPath(*args, **kwargs) -> Any: ...
def FrameRect(*args, **kwargs) -> Any: ...
def FrameRgn(*args, **kwargs) -> Any: ...
def GetActiveWindow(*args, **kwargs) -> Any: ...
def GetArcDirection(*args, **kwargs) -> Any: ...
def GetBkColor(*args, **kwargs) -> Any: ...
def GetBkMode(*args, **kwargs) -> Any: ...
def GetCapture(*args, **kwargs) -> Any: ...
def GetCaretPos(*args, **kwargs) -> Any: ...
def GetClassLong(*args, **kwargs) -> Any: ...
def GetClassName(*args, **kwargs) -> Any: ...
def GetClientRect(*args, **kwargs) -> Any: ...
def GetCurrentObject(*args, **kwargs) -> Any: ...
def GetCurrentPositionEx(*args, **kwargs) -> Any: ...
def GetCursor(*args, **kwargs) -> Any: ...
def GetCursorInfo(*args, **kwargs) -> Any: ...
def GetCursorPos(*args, **kwargs) -> Any: ...
def GetDC(*args, **kwargs) -> Any: ...
def GetDesktopWindow(*args, **kwargs) -> Any: ...
def GetDlgCtrlID(*args, **kwargs) -> Any: ...
def GetDlgItem(*args, **kwargs) -> Any: ...
def GetDlgItemInt(*args, **kwargs) -> Any: ...
def GetDlgItemText(*args, **kwargs) -> Any: ...
def GetDoubleClickTime(*args, **kwargs) -> Any: ...
def GetFocus(*args, **kwargs) -> Any: ...
def GetForegroundWindow(*args, **kwargs) -> Any: ...
def GetGraphicsMode(*args, **kwargs) -> Any: ...
def GetIconInfo(*args, **kwargs) -> Any: ...
def GetLayeredWindowAttributes(*args, **kwargs) -> Any: ...
def GetLayout(*args, **kwargs) -> Any: ...
def GetMapMode(*args, **kwargs) -> Any: ...
def GetMenu(*args, **kwargs) -> Any: ...
def GetMenuDefaultItem(*args, **kwargs) -> Any: ...
def GetMenuInfo(*args, **kwargs) -> Any: ...
def GetMenuItemCount(*args, **kwargs) -> Any: ...
def GetMenuItemID(*args, **kwargs) -> Any: ...
def GetMenuItemInfo(*args, **kwargs) -> Any: ...
def GetMenuItemRect(*args, **kwargs) -> Any: ...
def GetMenuState(*args, **kwargs) -> Any: ...
def GetMessage(*args, **kwargs) -> Any: ...
def GetMiterLimit(*args, **kwargs) -> Any: ...
def GetModuleHandle(*args, **kwargs) -> Any: ...
def GetNextDlgGroupItem(*args, **kwargs) -> Any: ...
def GetNextDlgTabItem(*args, **kwargs) -> Any: ...
def GetObject(*args, **kwargs) -> Any: ...
def GetObjectType(*args, **kwargs) -> Any: ...
def GetOpenFileName(*args, **kwargs) -> Any: ...
def GetOpenFileNameW(*args, **kwargs) -> Any: ...
def GetParent(*args, **kwargs) -> Any: ...
def GetPath(*args, **kwargs) -> Any: ...
def GetPixel(*args, **kwargs) -> Any: ...
def GetPolyFillMode(*args, **kwargs) -> Any: ...
def GetROP2(*args, **kwargs) -> Any: ...
def GetRgnBox(*args, **kwargs) -> Any: ...
def GetSaveFileNameW(*args, **kwargs) -> Any: ...
def GetScrollInfo(*args, **kwargs) -> Any: ...
def GetStockObject(*args, **kwargs) -> Any: ...
def GetStretchBltMode(*args, **kwargs) -> Any: ...
def GetSubMenu(*args, **kwargs) -> Any: ...
def GetSysColor(*args, **kwargs) -> Any: ...
def GetSysColorBrush(*args, **kwargs) -> Any: ...
def GetSystemMenu(*args, **kwargs) -> Any: ...
def GetTextAlign(*args, **kwargs) -> Any: ...
def GetTextCharacterExtra(*args, **kwargs) -> Any: ...
def GetTextColor(*args, **kwargs) -> Any: ...
def GetTextExtentPoint32(*args, **kwargs) -> Any: ...
def GetTextFace(*args, **kwargs) -> Any: ...
def GetTextMetrics(*args, **kwargs) -> Any: ...
def GetUpdateRgn(*args, **kwargs) -> Any: ...
def GetViewportExtEx(*args, **kwargs) -> Any: ...
def GetViewportOrgEx(*args, **kwargs) -> Any: ...
def GetWindow(*args, **kwargs) -> Any: ...
def GetWindowDC(*args, **kwargs) -> Any: ...
def GetWindowExtEx(*args, **kwargs) -> Any: ...
def GetWindowLong(*args, **kwargs) -> Any: ...
def GetWindowOrgEx(*args, **kwargs) -> Any: ...
def GetWindowPlacement(*args, **kwargs) -> Any: ...
def GetWindowRect(*args, **kwargs) -> Any: ...
def GetWindowRgn(*args, **kwargs) -> Any: ...
def GetWindowText(*args, **kwargs) -> Any: ...
def GetWindowTextLength(*args, **kwargs) -> Any: ...
def GetWorldTransform(*args, **kwargs) -> Any: ...
def GradientFill(*args, **kwargs) -> Any: ...
def HIWORD(*args, **kwargs) -> Any: ...
def HideCaret(*args, **kwargs) -> Any: ...
def ImageList_Add(*args, **kwargs) -> Any: ...
def ImageList_Create(*args, **kwargs) -> Any: ...
def ImageList_Destroy(*args, **kwargs) -> Any: ...
def ImageList_Draw(*args, **kwargs) -> Any: ...
def ImageList_DrawEx(*args, **kwargs) -> Any: ...
def ImageList_GetIcon(*args, **kwargs) -> Any: ...
def ImageList_GetImageCount(*args, **kwargs) -> Any: ...
def ImageList_LoadBitmap(*args, **kwargs) -> Any: ...
def ImageList_LoadImage(*args, **kwargs) -> Any: ...
def ImageList_Remove(*args, **kwargs) -> Any: ...
def ImageList_Replace(*args, **kwargs) -> Any: ...
def ImageList_ReplaceIcon(*args, **kwargs) -> Any: ...
def ImageList_SetBkColor(*args, **kwargs) -> Any: ...
def ImageList_SetOverlayImage(*args, **kwargs) -> Any: ...
def InitCommonControls(*args, **kwargs) -> Any: ...
def InitCommonControlsEx(*args, **kwargs) -> Any: ...
def InsertMenu(*args, **kwargs) -> Any: ...
def InsertMenuItem(*args, **kwargs) -> Any: ...
def InvalidateRect(*args, **kwargs) -> Any: ...
def InvalidateRgn(*args, **kwargs) -> Any: ...
def InvertRect(*args, **kwargs) -> Any: ...
def InvertRgn(*args, **kwargs) -> Any: ...
def IsChild(*args, **kwargs) -> Any: ...
def IsIconic(*args, **kwargs) -> Any: ...
def IsWindow(*args, **kwargs) -> Any: ...
def IsWindowEnabled(*args, **kwargs) -> Any: ...
def IsWindowVisible(*args, **kwargs) -> Any: ...
def LOGFONT(*args, **kwargs) -> Any: ...
def LOWORD(*args, **kwargs) -> Any: ...
def LineTo(*args, **kwargs) -> Any: ...
def ListView_SortItems(*args, **kwargs) -> Any: ...
def ListView_SortItemsEx(*args, **kwargs) -> Any: ...
def LoadCursor(*args, **kwargs) -> Any: ...
def LoadIcon(*args, **kwargs) -> Any: ...
def LoadImage(*args, **kwargs) -> Any: ...
def LoadMenu(*args, **kwargs) -> Any: ...
def MaskBlt(*args, **kwargs) -> Any: ...
def MessageBeep(*args, **kwargs) -> Any: ...
def MessageBox(*args, **kwargs) -> Any: ...
def ModifyMenu(*args, **kwargs) -> Any: ...
def ModifyWorldTransform(*args, **kwargs) -> Any: ...
def MoveToEx(*args, **kwargs) -> Any: ...
def MoveWindow(*args, **kwargs) -> Any: ...
def OffsetRgn(*args, **kwargs) -> Any: ...
def PaintDesktop(*args, **kwargs) -> Any: ...
def PaintRgn(*args, **kwargs) -> Any: ...
def PatBlt(*args, **kwargs) -> Any: ...
def PathToRegion(*args, **kwargs) -> Any: ...
def PeekMessage(*args, **kwargs) -> Any: ...
def Pie(*args, **kwargs) -> Any: ...
def PlgBlt(*args, **kwargs) -> Any: ...
def PolyBezier(*args, **kwargs) -> Any: ...
def PolyBezierTo(*args, **kwargs) -> Any: ...
def Polygon(*args, **kwargs) -> Any: ...
def Polyline(*args, **kwargs) -> Any: ...
def PolylineTo(*args, **kwargs) -> Any: ...
def PostMessage(*args, **kwargs) -> Any: ...
def PostQuitMessage(*args, **kwargs) -> Any: ...
def PostThreadMessage(*args, **kwargs) -> Any: ...
def PtInRect(*args, **kwargs) -> Any: ...
def PtInRegion(*args, **kwargs) -> Any: ...
def PumpMessages(*args, **kwargs) -> Any: ...
def PumpWaitingMessages(*args, **kwargs) -> Any: ...
def PyGetArraySignedLong(*args, **kwargs) -> Any: ...
def PyGetBufferAddressAndLen(*args, **kwargs) -> Any: ...
def PyGetMemory(*args, **kwargs) -> Any: ...
def PyGetString(*args, **kwargs) -> Any: ...
def PyMakeBuffer(*args, **kwargs) -> Any: ...
def PySetMemory(*args, **kwargs) -> Any: ...
def PySetString(*args, **kwargs) -> Any: ...
def RectInRegion(*args, **kwargs) -> Any: ...
def Rectangle(*args, **kwargs) -> Any: ...
def RedrawWindow(*args, **kwargs) -> Any: ...
def RegisterClass(*args, **kwargs) -> Any: ...
def RegisterDeviceNotification(*args, **kwargs) -> Any: ...
def RegisterHotKey(*args, **kwargs) -> Any: ...
def RegisterWindowMessage(*args, **kwargs) -> Any: ...
def ReleaseCapture(*args, **kwargs) -> Any: ...
def ReleaseDC(*args, **kwargs) -> Any: ...
def RemoveMenu(*args, **kwargs) -> Any: ...
def ReplyMessage(*args, **kwargs) -> Any: ...
def RestoreDC(*args, **kwargs) -> Any: ...
def RoundRect(*args, **kwargs) -> Any: ...
def SaveDC(*args, **kwargs) -> Any: ...
def ScreenToClient(*args, **kwargs) -> Any: ...
def ScrollWindowEx(*args, **kwargs) -> Any: ...
def SelectObject(*args, **kwargs) -> Any: ...
def SendMessage(*args, **kwargs) -> Any: ...
def SendMessageTimeout(*args, **kwargs) -> Any: ...
def SetActiveWindow(*args, **kwargs) -> Any: ...
def SetArcDirection(*args, **kwargs) -> Any: ...
def SetBkColor(*args, **kwargs) -> Any: ...
def SetBkMode(*args, **kwargs) -> Any: ...
def SetCapture(*args, **kwargs) -> Any: ...
def SetCaretPos(*args, **kwargs) -> Any: ...
def SetCursor(*args, **kwargs) -> Any: ...
def SetDlgItemInt(*args, **kwargs) -> Any: ...
def SetDlgItemText(*args, **kwargs) -> Any: ...
def SetDoubleClickTime(*args, **kwargs) -> Any: ...
def SetFocus(*args, **kwargs) -> Any: ...
def SetForegroundWindow(*args, **kwargs) -> Any: ...
def SetGraphicsMode(*args, **kwargs) -> Any: ...
def SetLayeredWindowAttributes(*args, **kwargs) -> Any: ...
def SetLayout(*args, **kwargs) -> Any: ...
def SetMapMode(*args, **kwargs) -> Any: ...
def SetMenu(*args, **kwargs) -> Any: ...
def SetMenuDefaultItem(*args, **kwargs) -> Any: ...
def SetMenuInfo(*args, **kwargs) -> Any: ...
def SetMenuItemBitmaps(*args, **kwargs) -> Any: ...
def SetMenuItemInfo(*args, **kwargs) -> Any: ...
def SetMiterLimit(*args, **kwargs) -> Any: ...
def SetParent(*args, **kwargs) -> Any: ...
def SetPixel(*args, **kwargs) -> Any: ...
def SetPixelV(*args, **kwargs) -> Any: ...
def SetPolyFillMode(*args, **kwargs) -> Any: ...
def SetROP2(*args, **kwargs) -> Any: ...
def SetRectRgn(*args, **kwargs) -> Any: ...
def SetScrollInfo(*args, **kwargs) -> Any: ...
def SetStretchBltMode(*args, **kwargs) -> Any: ...
def SetTextAlign(*args, **kwargs) -> Any: ...
def SetTextCharacterExtra(*args, **kwargs) -> Any: ...
def SetTextColor(*args, **kwargs) -> Any: ...
def SetViewportExtEx(*args, **kwargs) -> Any: ...
def SetViewportOrgEx(*args, **kwargs) -> Any: ...
def SetWindowExtEx(*args, **kwargs) -> Any: ...
def SetWindowLong(*args, **kwargs) -> Any: ...
def SetWindowOrgEx(*args, **kwargs) -> Any: ...
def SetWindowPlacement(*args, **kwargs) -> Any: ...
def SetWindowPos(*args, **kwargs) -> Any: ...
def SetWindowRgn(*args, **kwargs) -> Any: ...
def SetWindowText(*args, **kwargs) -> Any: ...
def SetWorldTransform(*args, **kwargs) -> Any: ...
def Shell_NotifyIcon(*args, **kwargs) -> Any: ...
def ShowCaret(*args, **kwargs) -> Any: ...
def ShowWindow(*args, **kwargs) -> Any: ...
def StretchBlt(*args, **kwargs) -> Any: ...
def StrokeAndFillPath(*args, **kwargs) -> Any: ...
def StrokePath(*args, **kwargs) -> Any: ...
def SystemParametersInfo(*args, **kwargs) -> Any: ...
def TrackPopupMenu(*args, **kwargs) -> Any: ...
def TranslateAccelerator(*args, **kwargs) -> Any: ...
def TranslateMessage(*args, **kwargs) -> Any: ...
def TransparentBlt(*args, **kwargs) -> Any: ...
def UnregisterClass(*args, **kwargs) -> Any: ...
def UnregisterDeviceNotification(*args, **kwargs) -> Any: ...
def UpdateLayeredWindow(*args, **kwargs) -> Any: ...
def UpdateWindow(*args, **kwargs) -> Any: ...
def ValidateRect(*args, **kwargs) -> Any: ...
def ValidateRgn(*args, **kwargs) -> Any: ...
def WNDCLASS(*args, **kwargs) -> Any: ...
def WaitMessage(*args, **kwargs) -> Any: ...
def WidenPath(*args, **kwargs) -> Any: ...
def WindowFromDC(*args, **kwargs) -> Any: ...
def WindowFromPoint(*args, **kwargs) -> Any: ...
def lpstr(*args, **kwargs) -> Any: ...
def set_logger(*args, **kwargs) -> Any: ...
