from typing import Any

class error(Exception): ...

def Close(*args, **kwargs) -> Any: ...
def Copy(*args, **kwargs) -> Any: ...
def GetExpandedName(*args, **kwargs) -> Any: ...
def Init(*args, **kwargs) -> Any: ...
def OpenFile(*args, **kwargs) -> Any: ...
