from typing import Any

NMPWAIT_NOWAIT: int
NMPWAIT_USE_DEFAULT_WAIT: int
NMPWAIT_WAIT_FOREVER: int
PIPE_ACCESS_DUPLEX: int
PIPE_ACCESS_INBOUND: int
PIPE_ACCESS_OUTBOUND: int
PIPE_NOWAIT: int
PIPE_READMODE_BYTE: int
PIPE_READMODE_MESSAGE: int
PIPE_TYPE_BYTE: int
PIPE_TYPE_MESSAGE: int
PIPE_UNLIMITED_INSTANCES: int
PIPE_WAIT: int
UNICODE: int

class error(Exception): ...

def CallNamedPipe(*args, **kwargs) -> Any: ...
def ConnectNamedPipe(*args, **kwargs) -> Any: ...
def CreateNamedPipe(*args, **kwargs) -> Any: ...
def CreatePipe(*args, **kwargs) -> Any: ...
def DisconnectNamedPipe(*args, **kwargs) -> Any: ...
def FdCreatePipe(*args, **kwargs) -> Any: ...
def GetNamedPipeClientProcessId(*args, **kwargs) -> Any: ...
def GetNamedPipeClientSessionId(*args, **kwargs) -> Any: ...
def GetNamedPipeHandleState(*args, **kwargs) -> Any: ...
def GetNamedPipeInfo(*args, **kwargs) -> Any: ...
def GetNamedPipeServerProcessId(*args, **kwargs) -> Any: ...
def GetNamedPipeServerSessionId(*args, **kwargs) -> Any: ...
def GetOverlappedResult(*args, **kwargs) -> Any: ...
def PeekNamedPipe(*args, **kwargs) -> Any: ...
def SetNamedPipeHandleState(*args, **kwargs) -> Any: ...
def TransactNamedPipe(*args, **kwargs) -> Any: ...
def WaitNamedPipe(*args, **kwargs) -> Any: ...
def popen(*args, **kwargs) -> Any: ...
def popen2(*args, **kwargs) -> Any: ...
def popen3(*args, **kwargs) -> Any: ...
def popen4(*args, **kwargs) -> Any: ...
