# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import Any, type_check_only

from auth0.authentication.token_verifier import SignatureVerifier
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPublicKey

@type_check_only
class _SignatureVerifierAsync(SignatureVerifier):
    async def verify_signature_async(self, token: str) -> dict[str, Any]: ...

@type_check_only
class _SymmetricSignatureVerifierAsync(_SignatureVerifierAsync): ...

from auth0.authentication.token_verifier import JwksFetcher  # noqa: E402

@type_check_only
class _JwksFetcherAsync(JwksFetcher):
    async def get_key_async(self, key_id: str) -> RSAPublicKey: ...

@type_check_only
class _AsymmetricSignatureVerifierAsync(_SignatureVerifierAsync): ...

from auth0.authentication.token_verifier import TokenVerifier  # noqa: E402

@type_check_only
class _TokenVerifierAsync(TokenVerifier):
    async def verify_async(
        self, token: str, nonce: str | None = None, max_age: int | None = None, organization: str | None = None
    ) -> dict[str, Any]: ...
