from redis.typing import KeysT as KeysT, KeyT as KeyT

def list_or_args(keys: KeysT, args: tuple[KeyT, ...]) -> list[KeyT]: ...
def nativestr(x): ...
def delist(x): ...
def parse_to_list(response): ...
def parse_list_to_dict(response): ...
def parse_to_dict(response): ...
def random_string(length: int = 10) -> str: ...
def quote_string(v): ...
def decode_dict_keys(obj): ...
def stringify_param_value(value): ...
def get_protocol_version(client): ...
