from _typeshed import Incomplete
from typing_extensions import Literal

from pythonwin.pywin.mfc import dialog as dialog, docview as docview, object as object, window as window

def GetItemText(item): ...

class HierDialog(dialog.Dialog):
    hierList: Incomplete
    dlgID: Incomplete
    title: Incomplete
    def __init__(self, title, hierList, bitmapID=..., dlgID=..., dll: Incomplete | None = ..., childListBoxID=...) -> None: ...
    def OnInitDialog(self): ...

class HierList(object.Object):
    listControl: Incomplete
    bitmapID: Incomplete
    root: Incomplete
    listBoxId: Incomplete
    itemHandleMap: Incomplete
    filledItemHandlesMap: Incomplete
    bitmapMask: Incomplete
    def __init__(self, root, bitmapID=..., listBoxId: Incomplete | None = ..., bitmapMask: Incomplete | None = ...) -> None: ...
    def __getattr__(self, attr): ...
    def ItemFromHandle(self, handle): ...
    def SetStyle(self, newStyle) -> None: ...
    imageList: Incomplete
    notify_parent: Incomplete
    def HierInit(self, parent, listControl: Incomplete | None = ...) -> None: ...
    def DeleteAllItems(self) -> None: ...
    def HierTerm(self) -> None: ...
    def OnTreeItemDoubleClick(self, info, extra): ...
    def OnTreeItemExpanding(self, info, extra): ...
    def OnTreeItemSelChanged(self, info, extra): ...
    def AddSubList(self, parentHandle, subItems) -> None: ...
    def AddItem(self, parentHandle, item, hInsertAfter=...): ...
    def Refresh(self, hparent: Incomplete | None = ...) -> None: ...
    def AcceptRoot(self, root) -> None: ...
    def GetBitmapColumn(self, item): ...
    def GetSelectedBitmapColumn(self, item) -> Literal[0]: ...
    def CheckChangedChildren(self): ...
    def GetText(self, item): ...
    def PerformItemSelected(self, item) -> None: ...
    def TakeDefaultAction(self, item) -> None: ...

class HierListWithItems(HierList):
    def __init__(self, root, bitmapID=..., listBoxID: Incomplete | None = ..., bitmapMask: Incomplete | None = ...) -> None: ...
    def DelegateCall(self, fn): ...
    def GetBitmapColumn(self, item): ...
    def GetSelectedBitmapColumn(self, item): ...
    def IsExpandable(self, item): ...
    def GetText(self, item): ...
    def GetSubList(self, item): ...
    def PerformItemSelected(self, item): ...
    def TakeDefaultAction(self, item): ...

class HierListItem:
    def __init__(self) -> None: ...
    def GetText(self) -> None: ...
    def GetSubList(self) -> None: ...
    def IsExpandable(self) -> None: ...
    def GetBitmapColumn(self) -> None: ...
    def GetSelectedBitmapColumn(self) -> None: ...
    def __lt__(self, other): ...
    def __eq__(self, other): ...
