from _typeshed import Incomplete

# from win32.lib.pywintypes import IID  # Crashes stubtest
from typing_extensions import TypeAlias

IID: TypeAlias = Incomplete

CATID_ActiveScript: IID
CATID_ActiveScriptParse: IID
IID_IActiveScript: IID
IID_IActiveScriptError: IID
IID_IActiveScriptParse: IID
IID_IActiveScriptParseProcedure: IID
IID_IActiveScriptSite: IID
IID_IObjectSafety: IID
IID_IProvideMultipleClassInfo: IID
INTERFACESAFE_FOR_UNTRUSTED_CALLER: int
INTERFACESAFE_FOR_UNTRUSTED_DATA: int
INTERFACE_USES_DISPEX: int
INTERFACE_USES_SECURITY_MANAGER: int
MULTICLASSINFO_GETIIDPRIMARY: int
MULTICLASSINFO_GETIIDSOURCE: int
MULTICLASSINFO_GETNUMRESERVEDDISPIDS: int
MULTICLASSINFO_GETTYPEINFO: int
SCRIPTINFO_ALL_FLAGS: int
SCRIPTINFO_ITYPEINFO: int
SCRIPTINFO_IUNKNOWN: int
SCRIPTINTERRUPT_ALL_FLAGS: int
SCRIPTINTERRUPT_DEBUG: int
SCRIPTINTERRUPT_RAISEEXCEPTION: int
SCRIPTITEM_ALL_FLAGS: int
SCRIPTITEM_CODEONLY: int
SCRIPTITEM_GLOBALMEMBERS: int
SCRIPTITEM_ISPERSISTENT: int
SCRIPTITEM_ISSOURCE: int
SCRIPTITEM_ISVISIBLE: int
SCRIPTITEM_NOCODE: int
SCRIPTPROC_ALL_FLAGS: int
SCRIPTPROC_HOSTMANAGESSOURCE: int
SCRIPTPROC_IMPLICIT_PARENTS: int
SCRIPTPROC_IMPLICIT_THIS: int
SCRIPTSTATE_CLOSED: int
SCRIPTSTATE_CONNECTED: int
SCRIPTSTATE_DISCONNECTED: int
SCRIPTSTATE_INITIALIZED: int
SCRIPTSTATE_STARTED: int
SCRIPTSTATE_UNINITIALIZED: int
SCRIPTTEXT_ALL_FLAGS: int
SCRIPTTEXT_ISEXPRESSION: int
SCRIPTTEXT_ISPERSISTENT: int
SCRIPTTEXT_ISVISIBLE: int
SCRIPTTHREADSTATE_NOTINSCRIPT: int
SCRIPTTHREADSTATE_RUNNING: int
SCRIPTTYPELIB_ISCONTROL: int
SCRIPTTYPELIB_ISPERSISTENT: int
SCRIPT_E_REPORTED: int
TIFLAGS_EXTENDDISPATCHONLY: int
