from _typeshed import Incomplete
from typing import Any

PROFILE_CMD: str
RO_QUERY_CMD: str
QUERY_CMD: str
DELETE_CMD: str
SLOWLOG_CMD: str
CONFIG_CMD: str
LIST_CMD: str
EXPLAIN_CMD: str

class GraphCommands:
    def commit(self): ...
    version: Any
    def query(
        self,
        q,
        params: Incomplete | None = None,
        timeout: Incomplete | None = None,
        read_only: bool = False,
        profile: bool = False,
    ): ...
    def merge(self, pattern): ...
    def delete(self): ...
    nodes: Any
    edges: Any
    def flush(self) -> None: ...
    def bulk(self, **kwargs) -> None: ...
    def profile(self, query): ...
    def slowlog(self): ...
    def config(self, name, value: Incomplete | None = None, set: bool = False): ...
    def list_keys(self): ...
    def execution_plan(self, query, params: Incomplete | None = ...): ...
    def explain(self, query, params: Incomplete | None = None): ...

class AsyncGraphCommands(GraphCommands):
    version: Incomplete
    async def query(
        self, q, params: Incomplete | None = ..., timeout: Incomplete | None = ..., read_only: bool = ..., profile: bool = ...
    ): ...
    async def execution_plan(self, query, params: Incomplete | None = ...): ...
    async def explain(self, query, params: Incomplete | None = ...): ...
    nodes: Incomplete
    edges: Incomplete
    async def flush(self) -> None: ...  # type: ignore[override]  # Incompatible return type
