from _typeshed import Incomplete
from typing import Any

# from win32.lib.pywintypes import IID  # Crashes stubtest
from typing_extensions import TypeAlias, final

IID: TypeAlias = Incomplete

IID_IInitializeWithFile: IID
IID_IInitializeWithStream: IID
IID_INamedPropertyStore: IID
IID_IObjectWithPropertyKey: IID
IID_IPersistSerializedPropStorage: IID
IID_IPropertyChange: IID
IID_IPropertyChangeArray: IID
IID_IPropertyDescription: IID
IID_IPropertyDescriptionAliasInfo: IID
IID_IPropertyDescriptionList: IID
IID_IPropertyDescriptionSearchInfo: IID
IID_IPropertyEnumType: IID
IID_IPropertyEnumTypeList: IID
IID_IPropertyStore: IID
IID_IPropertyStoreCache: IID
IID_IPropertyStoreCapabilities: IID
IID_IPropertySystem: IID

@final
class PROPVARIANTType:
    vt: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def ChangeType(self, *args, **kwargs) -> Any: ...
    def GetValue(self, *args, **kwargs) -> Any: ...
    def ToString(self, *args, **kwargs) -> Any: ...
    def __delattr__(self, name) -> Any: ...
    def __setattr__(self, name, value) -> Any: ...

class error(Exception): ...

def PSCreateMemoryPropertyStore(*args, **kwargs) -> Any: ...
def PSCreatePropertyChangeArray(*args, **kwargs) -> Any: ...
def PSCreatePropertyStoreFromPropertySetStorage(*args, **kwargs) -> Any: ...
def PSCreateSimplePropertyChange(*args, **kwargs) -> Any: ...
def PSGetItemPropertyHandler(*args, **kwargs) -> Any: ...
def PSGetNameFromPropertyKey(*args, **kwargs) -> Any: ...
def PSGetNamedPropertyFromPropertyStorage(*args, **kwargs) -> Any: ...
def PSGetPropertyDescription(*args, **kwargs) -> Any: ...
def PSGetPropertyFromPropertyStorage(*args, **kwargs) -> Any: ...
def PSGetPropertyKeyFromName(*args, **kwargs) -> Any: ...
def PSGetPropertySystem(*args, **kwargs) -> Any: ...
def PSLookupPropertyHandlerCLSID(*args, **kwargs) -> Any: ...
def PSRegisterPropertySchema(*args, **kwargs) -> Any: ...
def PSUnregisterPropertySchema(*args, **kwargs) -> Any: ...
def SHGetPropertyStoreForWindow(*args, **kwargs) -> Any: ...
def SHGetPropertyStoreFromParsingName(*args, **kwargs) -> Any: ...
def SHSetDefaultProperties(*args, **kwargs) -> Any: ...
def StgDeserializePropVariant(*args, **kwargs) -> Any: ...
def StgSerializePropVariant(*args, **kwargs) -> Any: ...
