version = "2.18.*"
upstream_repository = "https://github.com/pygments/pygments"
# Need a setuptools version where pkg_resources is typed
requires = ["setuptools>=71.1", "types-docutils"]
partial_stub = true

[tool.stubtest]
stubtest_requirements = ["sphinx"]
ignore_missing_stub = true
