import asyncio as asyncio
from collections.abc import Callable, Coroutine
from typing import Any

from .langhelpers import memoized_property

def is_exit_exception(e): ...
def await_only(awaitable: Coroutine) -> Any: ...
def await_fallback(awaitable: Coroutine) -> Any: ...
async def greenlet_spawn(fn: Callable, *args, _require_await: bool = ..., **kwargs) -> Any: ...

class AsyncAdaptedLock:
    @memoized_property
    def mutex(self): ...
    def __enter__(self): ...
    def __exit__(self, *arg, **kw) -> None: ...

def get_event_loop(): ...
