from _typeshed import Incomplete

CATID_PythonCOMServer: str

def recurse_delete_key(path, base=...) -> None: ...
def RegisterServer(
    clsid,
    pythonInstString: Incomplete | None = ...,
    desc: Incomplete | None = ...,
    progID: Incomplete | None = ...,
    verProgID: Incomplete | None = ...,
    defIcon: Incomplete | None = ...,
    threadingModel: str = ...,
    policy: Incomplete | None = ...,
    catids=...,
    other=...,
    addPyComCat: Incomplete | None = ...,
    dispatcher: Incomplete | None = ...,
    clsctx: Incomplete | None = ...,
    addnPath: Incomplete | None = ...,
) -> None: ...
def GetUnregisterServerKeys(
    clsid, progID: Incomplete | None = ..., verProgID: Incomplete | None = ..., customKeys: Incomplete | None = ...
): ...
def UnregisterServer(
    clsid, progID: Incomplete | None = ..., verProgID: Incomplete | None = ..., customKeys: Incomplete | None = ...
) -> None: ...
def GetRegisteredServerOption(clsid, optionName): ...
def RegisterClasses(*classes, **flags) -> None: ...
def UnregisterClasses(*classes, **flags) -> None: ...
def UnregisterInfoClasses(*classes, **flags): ...
def ReExecuteElevated(flags) -> None: ...
def UseCommandLine(*classes, **flags): ...
def RegisterPyComCategory() -> None: ...
