from _typeshed import Incomplete

NCBNAMSZ: int
MAX_LANA: int
NAME_FLAGS_MASK: int
GROUP_NAME: int
UNIQUE_NAME: int
REGISTERING: int
REGISTERED: int
DEREGISTERED: int
DUPLICATE: int
DUPLICATE_DEREG: int
LISTEN_OUTSTANDING: int
CALL_PENDING: int
SESSION_ESTABLISHED: int
HANGUP_PENDING: int
HANGUP_COMPLETE: int
SESSION_ABORTED: int
ALL_TRANSPORTS: str
MS_NBF: str
NCBCALL: int
NCBLISTEN: int
NCBHANGUP: int
NCBSEND: int
NCBRECV: int
NCBRECVANY: int
NCBCHAINSEND: int
NCBDGSEND: int
NCBDGRECV: int
NCBDGSENDBC: int
NCBDGRECVBC: int
NCBADDNAME: int
NCBDELNAME: int
NCBRESET: int
NCBASTAT: int
NCBSSTAT: int
NCBCANCEL: int
NCBADDGRNAME: int
NCBENUM: int
NCBUNLINK: int
NCBSENDNA: int
NCBCHAINSENDNA: int
NCBLANSTALERT: int
NCBACTION: int
NCBFINDNAME: int
NCBTRACE: int
ASYNCH: int
NRC_GOODRET: int
NRC_BUFLEN: int
NRC_ILLCMD: int
NRC_CMDTMO: int
NRC_INCOMP: int
NRC_BADDR: int
NRC_SNUMOUT: int
NRC_NORES: int
NRC_SCLOSED: int
NRC_CMDCAN: int
NRC_DUPNAME: int
NRC_NAMTFUL: int
NRC_ACTSES: int
NRC_LOCTFUL: int
NRC_REMTFUL: int
NRC_ILLNN: int
NRC_NOCALL: int
NRC_NOWILD: int
NRC_INUSE: int
NRC_NAMERR: int
NRC_SABORT: int
NRC_NAMCONF: int
NRC_IFBUSY: int
NRC_TOOMANY: int
NRC_BRIDGE: int
NRC_CANOCCR: int
NRC_CANCEL: int
NRC_DUPENV: int
NRC_ENVNOTDEF: int
NRC_OSRESNOTAV: int
NRC_MAXAPPS: int
NRC_NOSAPS: int
NRC_NORESOURCES: int
NRC_INVADDRESS: int
NRC_INVDDID: int
NRC_LOCKFAIL: int
NRC_OPENERR: int
NRC_SYSTEM: int
NRC_PENDING: int
ADAPTER_STATUS_ITEMS: Incomplete
NAME_BUFFER_ITEMS: Incomplete
SESSION_HEADER_ITEMS: Incomplete
SESSION_BUFFER_ITEMS: Incomplete
LANA_ENUM_ITEMS: Incomplete
FIND_NAME_HEADER_ITEMS: Incomplete
FIND_NAME_BUFFER_ITEMS: Incomplete
ACTION_HEADER_ITEMS: Incomplete
NCB: Incomplete

def Netbios(ncb): ...

class NCBStruct:
    def __init__(self, items) -> None: ...
    def __setattr__(self, attr, val) -> None: ...

def ADAPTER_STATUS(): ...
def NAME_BUFFER(): ...
def SESSION_HEADER(): ...
def SESSION_BUFFER(): ...
def LANA_ENUM(): ...
def FIND_NAME_HEADER(): ...
def FIND_NAME_BUFFER(): ...
def ACTION_HEADER(): ...
def byte_to_int(b): ...
