def CheckRegisteredExe(exename) -> None: ...
def CheckPathString(pathString): ...
def CheckPythonPaths(verbose) -> None: ...
def CheckHelpFiles(verbose) -> None: ...
def CheckRegistry(verbose: int = ...) -> None: ...

__warningregistry__: dict[str, int]
