from _typeshed import Incomplete

error: Incomplete
counter_english_map: Incomplete

def find_pdh_counter_localized_name(english_name, machine_name: Incomplete | None = ...): ...
def GetPerformanceAttributes(
    object, counter, instance: Incomplete | None = ..., inum: int = ..., format=..., machine: Incomplete | None = ...
): ...
def FindPerformanceAttributesByName(
    instanceName,
    object: Incomplete | None = ...,
    counter: Incomplete | None = ...,
    format=...,
    machine: Incomplete | None = ...,
    bRefresh: int = ...,
): ...
def ShowAllProcesses() -> None: ...
def BrowseCallBackDemo(counters): ...
def browse(callback=..., title: str = ..., level=...) -> None: ...
