from _typeshed import Incomplete

VS_FFI_SIGNATURE: int
VS_FFI_STRUCVERSION: int
VS_FFI_FILEFLAGSMASK: int
VOS_NT_WINDOWS32: int
null_byte: Incomplete

def file_flags(debug): ...
def file_type(is_dll): ...
def VS_FIXEDFILEINFO(maj, min, sub, build, debug: int = ..., is_dll: int = ...): ...
def nullterm(s): ...
def pad32(s, extra: int = ...): ...
def addlen(s): ...
def String(key, value): ...
def StringTable(key, data): ...
def StringFileInfo(data): ...
def Var(key, value): ...
def VarFileInfo(data): ...
def VS_VERSION_INFO(maj, min, sub, build, sdata, vdata, debug: int = ..., is_dll: int = ...): ...
def stamp(pathname, options) -> None: ...
