from typing import Any

COleClientItem_activeState: int
COleClientItem_activeUIState: int
COleClientItem_emptyState: int
COleClientItem_loadedState: int
COleClientItem_openState: int
OLE_CHANGED: int
OLE_CHANGED_ASPECT: int
OLE_CHANGED_STATE: int
OLE_CLOSED: int
OLE_RENAMED: int
OLE_SAVED: int

def AfxOleInit(*args, **kwargs) -> Any: ...
def CreateInsertDialog(*args, **kwargs) -> Any: ...
def CreateOleClientItem(*args, **kwargs) -> Any: ...
def CreateOleDocument(*args, **kwargs) -> Any: ...
def DaoGetEngine(*args, **kwargs) -> Any: ...
def EnableBusyDialog(*args, **kwargs) -> Any: ...
def EnableNotRespondingDialog(*args, **kwargs) -> Any: ...
def GetIDispatchForWindow(*args, **kwargs) -> Any: ...
def OleGetUserCtrl(*args, **kwargs) -> Any: ...
def OleSetUserCtrl(*args, **kwargs) -> Any: ...
def SetMessagePendingDelay(*args, **kwargs) -> Any: ...
