from typing import Any

AFX_IDW_PANE_FIRST: int
AFX_IDW_PANE_LAST: int
AFX_WS_DEFAULT_VIEW: int
CDocTemplate_Confidence_maybeAttemptForeign: int
CDocTemplate_Confidence_maybeAttemptNative: int
CDocTemplate_Confidence_noAttempt: int
CDocTemplate_Confidence_yesAlreadyOpen: int
CDocTemplate_Confidence_yesAttemptForeign: int
CDocTemplate_Confidence_yesAttemptNative: int
CDocTemplate_docName: int
CDocTemplate_fileNewName: int
CDocTemplate_filterExt: int
CDocTemplate_filterName: int
CDocTemplate_regFileTypeId: int
CDocTemplate_regFileTypeName: int
CDocTemplate_windowTitle: int
CRichEditView_WrapNone: int
CRichEditView_WrapToTargetDevice: int
CRichEditView_WrapToWindow: int
FWS_ADDTOTITLE: int
FWS_PREFIXTITLE: int
FWS_SNAPTOBARS: int
IDB_BROWSER_HIER: int
IDB_DEBUGGER_HIER: int
IDB_HIERFOLDERS: int
IDC_ABOUT_VERSION: int
IDC_AUTOCOMPLETE: int
IDC_AUTO_RELOAD: int
IDC_BUTTON1: int
IDC_BUTTON2: int
IDC_BUTTON3: int
IDC_BUTTON4: int
IDC_CALLTIPS: int
IDC_CHECK1: int
IDC_CHECK2: int
IDC_CHECK3: int
IDC_COMBO1: int
IDC_COMBO2: int
IDC_DBG_ADD: int
IDC_DBG_BREAKPOINTS: int
IDC_DBG_CLEAR: int
IDC_DBG_CLOSE: int
IDC_DBG_GO: int
IDC_DBG_STACK: int
IDC_DBG_STEP: int
IDC_DBG_STEPOUT: int
IDC_DBG_STEPOVER: int
IDC_DBG_WATCH: int
IDC_EDIT1: int
IDC_EDIT2: int
IDC_EDIT3: int
IDC_EDIT4: int
IDC_EDITOR_COLOR: int
IDC_EDIT_TABS: int
IDC_FOLD_ENABLE: int
IDC_FOLD_ON_OPEN: int
IDC_FOLD_SHOW_LINES: int
IDC_INDENT_SIZE: int
IDC_KEYBOARD_CONFIG: int
IDC_LIST1: int
IDC_MARGIN_FOLD: int
IDC_MARGIN_LINENUMBER: int
IDC_MARGIN_MARKER: int
IDC_PROMPT1: int
IDC_PROMPT2: int
IDC_PROMPT3: int
IDC_PROMPT4: int
IDC_PROMPT_TABS: int
IDC_RADIO1: int
IDC_RADIO2: int
IDC_RIGHTEDGE_COLUMN: int
IDC_RIGHTEDGE_DEFINE: int
IDC_RIGHTEDGE_ENABLE: int
IDC_RIGHTEDGE_SAMPLE: int
IDC_SPIN1: int
IDC_SPIN2: int
IDC_SPIN3: int
IDC_TABTIMMY_BG: int
IDC_TABTIMMY_IND: int
IDC_TABTIMMY_NONE: int
IDC_TAB_SIZE: int
IDC_USE_SMART_TABS: int
IDC_USE_TABS: int
IDC_VIEW_EOL: int
IDC_VIEW_INDENTATIONGUIDES: int
IDC_VIEW_WHITESPACE: int
IDC_VSS_INTEGRATE: int
IDD_ABOUTBOX: int
IDD_DUMMYPROPPAGE: int
IDD_GENERAL_STATUS: int
IDD_LARGE_EDIT: int
IDD_PP_DEBUGGER: int
IDD_PP_EDITOR: int
IDD_PP_FORMAT: int
IDD_PP_IDE: int
IDD_PP_TABS: int
IDD_PP_TOOLMENU: int
IDD_PROPDEMO1: int
IDD_PROPDEMO2: int
IDD_RUN_SCRIPT: int
IDD_SET_TABSTOPS: int
IDD_SIMPLE_INPUT: int
IDD_TREE: int
IDD_TREE_MB: int
IDR_CNTR_INPLACE: int
IDR_DEBUGGER: int
IDR_MAINFRAME: int
IDR_PYTHONCONTYPE: int
IDR_PYTHONTYPE: int
IDR_PYTHONTYPE_CNTR_IP: int
IDR_TEXTTYPE: int
ID_APP_ABOUT: int
ID_APP_EXIT: int
ID_EDIT_CLEAR: int
ID_EDIT_CLEAR_ALL: int
ID_EDIT_COPY: int
ID_EDIT_CUT: int
ID_EDIT_FIND: int
ID_EDIT_GOTO_LINE: int
ID_EDIT_PASTE: int
ID_EDIT_REDO: int
ID_EDIT_REPEAT: int
ID_EDIT_REPLACE: int
ID_EDIT_SELECT_ALL: int
ID_EDIT_SELECT_BLOCK: int
ID_EDIT_UNDO: int
ID_FILE_CHECK: int
ID_FILE_CLOSE: int
ID_FILE_IMPORT: int
ID_FILE_LOCATE: int
ID_FILE_MRU_FILE1: int
ID_FILE_MRU_FILE2: int
ID_FILE_MRU_FILE3: int
ID_FILE_MRU_FILE4: int
ID_FILE_NEW: int
ID_FILE_OPEN: int
ID_FILE_PAGE_SETUP: int
ID_FILE_PRINT: int
ID_FILE_PRINT_PREVIEW: int
ID_FILE_PRINT_SETUP: int
ID_FILE_RUN: int
ID_FILE_SAVE: int
ID_FILE_SAVE_ALL: int
ID_FILE_SAVE_AS: int
ID_HELP_GUI_REF: int
ID_HELP_OTHER: int
ID_HELP_PYTHON: int
ID_INDICATOR_COLNUM: int
ID_INDICATOR_LINENUM: int
ID_NEXT_PANE: int
ID_PREV_PANE: int
ID_SEPARATOR: int
ID_VIEW_BROWSE: int
ID_VIEW_EOL: int
ID_VIEW_FIXED_FONT: int
ID_VIEW_FOLD_COLLAPSE: int
ID_VIEW_FOLD_COLLAPSE_ALL: int
ID_VIEW_FOLD_EXPAND: int
ID_VIEW_FOLD_EXPAND_ALL: int
ID_VIEW_FOLD_TOPLEVEL: int
ID_VIEW_INDENTATIONGUIDES: int
ID_VIEW_INTERACTIVE: int
ID_VIEW_OPTIONS: int
ID_VIEW_RIGHT_EDGE: int
ID_VIEW_STATUS_BAR: int
ID_VIEW_TOOLBAR: int
ID_VIEW_TOOLBAR_DBG: int
ID_VIEW_WHITESPACE: int
ID_WINDOW_ARRANGE: int
ID_WINDOW_CASCADE: int
ID_WINDOW_NEW: int
ID_WINDOW_SPLIT: int
ID_WINDOW_TILE_HORZ: int
ID_WINDOW_TILE_VERT: int
LM_COMMIT: int
LM_HORZ: int
LM_HORZDOCK: int
LM_LENGTHY: int
LM_MRUWIDTH: int
LM_STRETCH: int
LM_VERTDOCK: int
MFS_4THICKFRAME: int
MFS_BLOCKSYSMENU: int
MFS_MOVEFRAME: int
MFS_SYNCACTIVE: int
MFS_THICKFRAME: int
PD_ALLPAGES: int
PD_COLLATE: int
PD_DISABLEPRINTTOFILE: int
PD_ENABLEPRINTHOOK: int
PD_ENABLEPRINTTEMPLATE: int
PD_ENABLEPRINTTEMPLATEHANDLE: int
PD_ENABLESETUPHOOK: int
PD_ENABLESETUPTEMPLATE: int
PD_ENABLESETUPTEMPLATEHANDLE: int
PD_HIDEPRINTTOFILE: int
PD_NONETWORKBUTTON: int
PD_NOPAGENUMS: int
PD_NOSELECTION: int
PD_NOWARNING: int
PD_PAGENUMS: int
PD_PRINTSETUP: int
PD_PRINTTOFILE: int
PD_RETURNDC: int
PD_RETURNDEFAULT: int
PD_RETURNIC: int
PD_SELECTION: int
PD_SHOWHELP: int
PD_USEDEVMODECOPIES: int
PD_USEDEVMODECOPIESANDCOLLATE: int
PSWIZB_BACK: int
PSWIZB_DISABLEDFINISH: int
PSWIZB_FINISH: int
PSWIZB_NEXT: int
UNICODE: int
copyright: str
debug: int
dllhandle: int
types: dict[str, type]

class error(Exception): ...

def AddToRecentFileList(*args, **kwargs) -> Any: ...
def ComparePath(*args, **kwargs) -> Any: ...
def CreateBitmap(*args, **kwargs) -> Any: ...
def CreateBitmapFromHandle(*args, **kwargs) -> Any: ...
def CreateBrush(*args, **kwargs) -> Any: ...
def CreateButton(*args, **kwargs) -> Any: ...
def CreateColorDialog(*args, **kwargs) -> Any: ...
def CreateControl(*args, **kwargs) -> Any: ...
def CreateControlBar(*args, **kwargs) -> Any: ...
def CreateCtrlView(*args, **kwargs) -> Any: ...
def CreateDC(*args, **kwargs) -> Any: ...
def CreateDCFromHandle(*args, **kwargs) -> Any: ...
def CreateDebuggerThread(*args, **kwargs) -> Any: ...
def CreateDialog(*args, **kwargs) -> Any: ...
def CreateDialogBar(*args, **kwargs) -> Any: ...
def CreateDialogIndirect(*args, **kwargs) -> Any: ...
def CreateDocTemplate(*args, **kwargs) -> Any: ...
def CreateEdit(*args, **kwargs) -> Any: ...
def CreateEditView(*args, **kwargs) -> Any: ...
def CreateFileDialog(*args, **kwargs) -> Any: ...
def CreateFont(*args, **kwargs) -> Any: ...
def CreateFontDialog(*args, **kwargs) -> Any: ...
def CreateFormView(*args, **kwargs) -> Any: ...
def CreateFrame(*args, **kwargs) -> Any: ...
def CreateImageList(*args, **kwargs) -> Any: ...
def CreateListCtrl(*args, **kwargs) -> Any: ...
def CreateListView(*args, **kwargs) -> Any: ...
def CreateMDIChild(*args, **kwargs) -> Any: ...
def CreateMDIFrame(*args, **kwargs) -> Any: ...
def CreateMenu(*args, **kwargs) -> Any: ...
def CreatePalette(*args, **kwargs) -> Any: ...
def CreatePen(*args, **kwargs) -> Any: ...
def CreatePopupMenu(*args, **kwargs) -> Any: ...
def CreatePrintDialog(*args, **kwargs) -> Any: ...
def CreateProgressCtrl(*args, **kwargs) -> Any: ...
def CreatePropertyPage(*args, **kwargs) -> Any: ...
def CreatePropertyPageIndirect(*args, **kwargs) -> Any: ...
def CreatePropertySheet(*args, **kwargs) -> Any: ...
def CreateRectRgn(*args, **kwargs) -> Any: ...
def CreateRgn(*args, **kwargs) -> Any: ...
def CreateRichEditCtrl(*args, **kwargs) -> Any: ...
def CreateRichEditDocTemplate(*args, **kwargs) -> Any: ...
def CreateRichEditView(*args, **kwargs) -> Any: ...
def CreateSliderCtrl(*args, **kwargs) -> Any: ...
def CreateSplitter(*args, **kwargs) -> Any: ...
def CreateStatusBar(*args, **kwargs) -> Any: ...
def CreateStatusBarCtrl(*args, **kwargs) -> Any: ...
def CreateThread(*args, **kwargs) -> Any: ...
def CreateToolBar(*args, **kwargs) -> Any: ...
def CreateToolBarCtrl(*args, **kwargs) -> Any: ...
def CreateToolTipCtrl(*args, **kwargs) -> Any: ...
def CreateTreeCtrl(*args, **kwargs) -> Any: ...
def CreateTreeView(*args, **kwargs) -> Any: ...
def CreateView(*args, **kwargs) -> Any: ...
def CreateWindowFromHandle(*args, **kwargs) -> Any: ...
def CreateWnd(*args, **kwargs) -> Any: ...
def DestroyDebuggerThread(*args, **kwargs) -> Any: ...
def DisplayTraceback(*args, **kwargs) -> Any: ...
def DoWaitCursor(*args, **kwargs) -> Any: ...
def Enable3dControls(*args, **kwargs) -> Any: ...
def EnableControlContainer(*args, **kwargs) -> Any: ...
def FindWindow(*args, **kwargs) -> Any: ...
def FindWindowEx(*args, **kwargs) -> Any: ...
def FullPath(*args, **kwargs) -> Any: ...
def GetActiveWindow(*args, **kwargs) -> Any: ...
def GetApp(*args, **kwargs) -> Any: ...
def GetAppName(*args, **kwargs) -> Any: ...
def GetAppRegistryKey(*args, **kwargs) -> Any: ...
def GetBytes(*args, **kwargs) -> Any: ...
def GetCommandLine(*args, **kwargs) -> Any: ...
def GetDeviceCaps(*args, **kwargs) -> Any: ...
def GetFileTitle(*args, **kwargs) -> Any: ...
def GetFocus(*args, **kwargs) -> Any: ...
def GetForegroundWindow(*args, **kwargs) -> Any: ...
def GetHalftoneBrush(*args, **kwargs) -> Any: ...
def GetInitialStateRequest(*args, **kwargs) -> Any: ...
def GetMainFrame(*args, **kwargs) -> Any: ...
def GetName(*args, **kwargs) -> Any: ...
def GetProfileFileName(*args, **kwargs) -> Any: ...
def GetProfileVal(*args, **kwargs) -> Any: ...
def GetRecentFileList(*args, **kwargs) -> Any: ...
def GetResource(*args, **kwargs) -> Any: ...
def GetThread(*args, **kwargs) -> Any: ...
def GetType(*args, **kwargs) -> Any: ...
def InitRichEdit(*args, **kwargs) -> Any: ...
def InstallCallbackCaller(*args, **kwargs) -> Any: ...
def IsDebug(*args, **kwargs) -> Any: ...
def IsObject(*args, **kwargs) -> Any: ...
def IsWin32s(*args, **kwargs) -> Any: ...
def LoadDialogResource(*args, **kwargs) -> Any: ...
def LoadLibrary(*args, **kwargs) -> Any: ...
def LoadMenu(*args, **kwargs) -> Any: ...
def LoadStdProfileSettings(*args, **kwargs) -> Any: ...
def LoadString(*args, **kwargs) -> Any: ...
def MessageBox(*args, **kwargs) -> Any: ...
def OutputDebug(*args, **kwargs) -> Any: ...
def OutputDebugString(*args, **kwargs) -> Any: ...
def PrintTraceback(*args, **kwargs) -> Any: ...
def PumpWaitingMessages(*args, **kwargs) -> Any: ...
def RegisterWndClass(*args, **kwargs) -> Any: ...
def RemoveRecentFile(*args, **kwargs) -> Any: ...
def SetAppHelpPath(*args, **kwargs) -> Any: ...
def SetAppName(*args, **kwargs) -> Any: ...
def SetCurrentInstanceHandle(*args, **kwargs) -> Any: ...
def SetCurrentResourceHandle(*args, **kwargs) -> Any: ...
def SetDialogBkColor(*args, **kwargs) -> Any: ...
def SetProfileFileName(*args, **kwargs) -> Any: ...
def SetRegistryKey(*args, **kwargs) -> Any: ...
def SetResource(*args, **kwargs) -> Any: ...
def SetStatusText(*args, **kwargs) -> Any: ...
def StartDebuggerPump(*args, **kwargs) -> Any: ...
def StopDebuggerPump(*args, **kwargs) -> Any: ...
def TranslateMessage(*args, **kwargs) -> Any: ...
def TranslateVirtualKey(*args, **kwargs) -> Any: ...
def WinHelp(*args, **kwargs) -> Any: ...
def WriteProfileVal(*args, **kwargs) -> Any: ...
